# MRI processing

In [1]:
# import libraries
import numpy as np 
import pandas as pd 
import os, fnmatch
import nibabel as nib
import matplotlib.pyplot as plt
from scipy.stats import iqr

from joblib import Parallel, delayed
import logging

In [34]:
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', 30)

In [35]:
# upload metafile
#meta2 = pd.read_csv('metafile_completing/metafile_completed_ADNI_A4_processed_02_06_2024.csv') #shuffled on 10_04_2025
#meta2= meta2.sample(frac=1, ignore_index = True)
#meta2.to_csv('metafile_completing/metafile_completed_ADNI_A4_processed_02_06_2024_shuffled.csv')

meta2 = pd.read_csv('metafile_completing/metafile_completed_ADNI_A4_processed_02_06_2024_shuffled.csv')

In [36]:
meta2['Modality'].value_counts()

MRI    42804
PET    22476
Name: Modality, dtype: int64

In [37]:
# selecting all MRI and only amyloid PET scans
pd.set_option('display.max_rows', 20)
meta3 = meta2[(meta2.Modality == 'MRI') | 
      (meta2.modality_subtype == 'AV45')]#|
#     (meta2.modality_subtype == 'FBB')|
#     (meta2.modality_subtype == 'PIB')]

In [38]:
# selecting only T1 and amyloid PET scans with needed pre-proccesing 
'''meta4 = meta3[((meta3.Project == 'ADNI')&((meta3.Description.str.contains('MP*RAGE|T1|IR*SPGR')) | 
     (meta3.Description.str.contains('Co-registered, Averaged'))))|
           (( meta3.Project == 'A4')&((meta3.modality_subtype.str.contains('T1')) | 
     (meta3.Description.str.contains('Flor*'))))]'''

"meta4 = meta3[((meta3.Project == 'ADNI')&((meta3.Description.str.contains('MP*RAGE|T1|IR*SPGR')) | \n     (meta3.Description.str.contains('Co-registered, Averaged'))))|\n           (( meta3.Project == 'A4')&((meta3.modality_subtype.str.contains('T1')) | \n     (meta3.Description.str.contains('Flor*'))))]"

In [39]:
pet_mask = ((meta3.Modality == 'PET')&(meta3.Description.str.contains('Co-registered, Averaged')|
            meta3.Description.str.contains('^Flor.*')))
mri_mask = (meta3.Modality == 'MRI')&(meta3.Description.str.contains('MP.*RAGE|T1|IR.*SPGR')|
            meta3.modality_subtype.str.contains('T1'))

In [40]:
meta4 = meta3[pet_mask|mri_mask]
meta4.reset_index(drop=True, inplace = True)

In [41]:
meta4[meta4.Project == 'A4'].modality_subtype.value_counts()

AV45    4486
T1      1878
Name: modality_subtype, dtype: int64

In [42]:
#pd.set_option('display.max_rows', None)
meta4[meta4.Project == 'ADNI'].modality_subtype.value_counts()

MPRAGE                         10738
MPRAGE GRAPPA2                  4104
MP-RAGE                         3600
AV45                            3004
MPRAGE Repeat                   2193
                               ...
SAG 3D MPRAGE, no angle            1
Accelerated Satittal MPRAGE        1
MPRAGE_repeat                      1
REPEAT MP-RAGE                     1
MPRAGE-REPEAT                      1
Name: modality_subtype, Length: 171, dtype: int64

In [43]:
meta4 = meta4.copy()
meta4['year'] = ''
for i in range(meta4.shape[0]):
    meta4['year'].values[i] = meta4['Study.Date'].values[i].split('/')[2]

In [44]:
meta4['Modality'].value_counts()

MRI    37003
PET     7490
Name: Modality, dtype: int64

In [45]:
pet_meta = meta4[meta4.Modality == 'PET']
pet_meta.reset_index(drop=True, inplace = True)

mri_meta = meta4[meta4.Modality == 'MRI']
mri_meta.reset_index(drop=True, inplace = True)

In [46]:
pet_meta.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Subject.ID', 'Project', 'Phase', 'Sex',
       'Weight', 'Research.Group', 'Visit', 'Study.Date', 'Archive.Date',
       'Age', 'Modality', 'Description', 'Type', 'Imaging.Protocol',
       'Image.ID', 'VISCODE', 'Image.Data.ID', 'modality_subtype', 'PATH',
       'year'],
      dtype='object')

In [47]:

pet_mri_tab = pet_meta[['Subject.ID','Project','Phase' ,'Sex','Weight','Research.Group','VISCODE','Study.Date','Age','Modality','Description','Imaging.Protocol','Image.Data.ID','modality_subtype','PATH']]
pet_mri_tab = pet_mri_tab.copy()
pet_mri_tab['MRI_subID']= ''
pet_mri_tab['MRI_Modality']= ''
pet_mri_tab['MRI_Research.Group']= ''
pet_mri_tab['MRI_Age']= np.nan
pet_mri_tab['MRI_VISCODE']= ''
pet_mri_tab['MRI_studydate']= ''
pet_mri_tab['MRI_Research.Group']= ''
pet_mri_tab['MRI_Description']= ''
pet_mri_tab['MRI_Imaging.protocol']= ''
pet_mri_tab['MRI_Type']= ''
pet_mri_tab['MRI_ID']= ''
pet_mri_tab['MRI_PATH']= ''

In [48]:
pet_meta.shape[0]

7490

In [49]:
pet_meta['Phase'].value_counts()

ADNI 2     1886
ADNI 3      863
ADNI GO     255
Name: Phase, dtype: int64

In [50]:
pet_meta['VISCODE'].value_counts()

SCV2    4486
v03      754
v21      521
bl       362
init     313
y2       263
v41      251
v11      160
v31      113
m48       87
v06       67
y4        49
m60       37
v51       20
m36        7
Name: VISCODE, dtype: int64

In [51]:
# let's try again 

suc = 0 
er = 0

#for i in range(1992):
for i in range(pet_meta.shape[0]):
    pet_id = pet_meta.iloc[i,:]
    
    mri_data = mri_meta.copy()
    
    mri_data= mri_data[mri_data['Subject.ID']==pet_id['Subject.ID']]
                        
    mri_data['age_diff'] = abs(float(pet_id.Age) - mri_data.Age.astype(float))
    
    mri_data= mri_data[((mri_data['Age'] == pet_id['Age'])
                        | (mri_data['VISCODE'] == pet_id['VISCODE'])
                        |(abs(mri_data.age_diff)<=1))]
                          
    if mri_data.shape[0]== 0:
        er += 1
        del mri_data
        print(str(i) + ' '+ pet_id['Subject.ID']+' error')
        continue
        
    ideal_mri = mri_data[mri_data['VISCODE'] == pet_id['VISCODE']]
    if ideal_mri.shape[0] == 0:
        ideal_mri = mri_data[mri_data['Age'] == pet_id['Age']]
    if ideal_mri.shape[0] == 0:
        ideal_mri = mri_data[mri_data.age_diff == mri_data.age_diff.min()]
    if ideal_mri.shape[0] == 0:
        er += 1
        del mri_data
        print(str(i) + ' '+ pet_id['Subject.ID']+' error')
        continue
            
    mri_data_orig = ideal_mri[ideal_mri['Type'] == 'Original']
    mri_data_proc = ideal_mri[ideal_mri['Type'] == 'Processed']
    
    if pet_id['Phase'] == 'ADNI 3' and mri_data_orig.shape[0]>0:
        suc += 1
        pet_mri_tab['MRI_subID'].values[i]= mri_data_orig.iloc[0,:]['Subject.ID']
        pet_mri_tab['MRI_Modality'].values[i]= mri_data_orig.iloc[0,:]['Modality']
        pet_mri_tab['MRI_Research.Group'].values[i]= mri_data_orig.iloc[0,:]['Research.Group']
        pet_mri_tab['MRI_Age'].values[i]= mri_data_orig.iloc[0,:]['Age']
        pet_mri_tab['MRI_VISCODE'].values[i]= mri_data_orig.iloc[0,:]['VISCODE']
        pet_mri_tab['MRI_studydate'].values[i]= mri_data_orig.iloc[0,:]['Study.Date']
        pet_mri_tab['MRI_Description'].values[i]= mri_data_orig.iloc[0,:]['Description']
        pet_mri_tab['MRI_Imaging.protocol'].values[i]= mri_data_orig.iloc[0,:]['Imaging.Protocol']
        pet_mri_tab['MRI_Type'].values[i]= mri_data_orig.iloc[0,:]['Type']
        pet_mri_tab['MRI_ID'].values[i]= mri_data_orig.iloc[0,:]['Image.Data.ID']
        pet_mri_tab['MRI_PATH'].values[i]= mri_data_orig.iloc[0,:]['PATH']

    elif ((pet_id['Phase'] != 'ADNI 3' and mri_data_proc.shape[0]>0) or 
          (pet_id['Project'] == 'A4' and mri_data_proc.shape[0]>0)):
        suc += 1
        pet_mri_tab['MRI_subID'].values[i]= mri_data_proc.iloc[0,:]['Subject.ID']
        pet_mri_tab['MRI_Modality'].values[i]= mri_data_proc.iloc[0,:]['Modality']
        pet_mri_tab['MRI_Research.Group'].values[i]= mri_data_proc.iloc[0,:]['Research.Group']
        pet_mri_tab['MRI_Age'].values[i]= mri_data_proc.iloc[0,:]['Age']
        pet_mri_tab['MRI_VISCODE'].values[i]= mri_data_proc.iloc[0,:]['VISCODE']
        pet_mri_tab['MRI_studydate'].values[i]= mri_data_proc.iloc[0,:]['Study.Date']
        pet_mri_tab['MRI_Description'].values[i]= mri_data_proc.iloc[0,:]['Description']
        pet_mri_tab['MRI_Imaging.protocol'].values[i]= mri_data_proc.iloc[0,:]['Imaging.Protocol']
        pet_mri_tab['MRI_Type'].values[i]= mri_data_proc.iloc[0,:]['Type']
        pet_mri_tab['MRI_ID'].values[i]= mri_data_proc.iloc[0,:]['Image.Data.ID']
        pet_mri_tab['MRI_PATH'].values[i]= mri_data_proc.iloc[0,:]['PATH']

0 B61659759 error
3 B49983219 error
7 B87425311 error
10 B90196559 error
11 B47761872 error
15 B75038203 error
16 B60794280 error
32 B18601506 error
34 B38322283 error
37 B77307945 error
41 B84642422 error
42 B55412026 error
43 B67551148 error
47 B63119332 error
52 B28071973 error
53 B48916189 error
54 B93878024 error
56 B48995724 error
60 B75984003 error
61 B16386965 error
62 B41388843 error
63 B92918238 error
65 B18581535 error
67 B75057616 error
70 B15283443 error
72 B86955049 error
75 B78518223 error
76 B68756730 error
77 B31427401 error
79 B15099158 error
84 B44674253 error
86 B68104601 error
90 B71778346 error
91 B60427965 error
93 B75863045 error
96 B97669016 error
100 B55663696 error
101 B70058389 error
104 B72085567 error
108 B72869324 error
111 B58827256 error
117 B43590060 error
119 B46644870 error
120 B72580739 error
121 B32093768 error
125 B22846057 error
126 B99577525 error
127 B99367143 error
131 B67984752 error
132 B43447426 error
136 B97948712 error
141 B43634812 error
145 B35480522 error
146 B86092610 error
147 B75793840 error
148 B58539791 error
149 B47359998 error
153 B67368341 error
154 094_S_4234 error
155 B20862398 error
156 B43945629 error
159 B94084416 error
160 B19232701 error
165 127_S_0684 error
166 B98109660 error
167 B61158332 error
168 B99385084 error
170 B46667665 error
171 B50437412 error
172 B89808868 error
174 B84268201 error
178 B91395141 error
184 B53177666 error
186 B90887798 error
190 B32472475 error
192 B15815229 error
196 B11885466 error
199 B44572235 error
200 B55967033 error
202 B74663723 error
208 B54987529 error
216 B81074830 error
217 B87782002 error
225 B72546677 error
226 B40171747 error
227 B89520089 error
234 B37750685 error
236 B31028381 error
237 012_S_4849 error
238 B37235863 error
240 B16360084 error
244 B99809023 error
247 B10959142 error
248 B45438242 error
250 B45742169 error
252 B93695923 error
253 B70180225 error
254 127_S_0684 error
255 B31366095 error
258 B44924439 error
263 B57009531 error
267 B44308727 error
268 B56975652 error
270 B98372093 error
272 B47661057 error
273 B85962014 error
274 B78924796 error
277 B77754193 error
282 B83613858 error
285 B30044798 error
287 B20644236 error
288 B86323141 error
290 B79524689 error
293 B92692197 error
297 B75443153 error
300 B61634247 error
301 018_S_4349 error
302 B87884106 error
303 B53941266 error
304 B46596266 error
307 B41080548 error
314 B13137671 error
318 B48160866 error
329 B66851696 error
330 B75731704 error
334 B20893730 error
336 B81747169 error
337 B29147344 error
338 B50554230 error
339 B52856025 error
340 B43425691 error
342 B51381148 error
344 B73749107 error
345 022_S_0096 error
346 B43293661 error
347 B89834958 error
348 B84285014 error
349 B31190920 error
351 B81135675 error
353 B15134132 error
359 B39142632 error
360 B66633343 error
363 B70896084 error
365 B46432644 error
366 B13189204 error
368 B11819993 error
369 B11941178 error
370 B18153322 error
371 B71440029 error
374 B87392763 error
375 B54577358 error
376 B89072313 error
377 B46415731 error
381 B58573574 error
390 B26767668 error
391 B54465001 error
394 B32754158 error
395 B96941144 error
397 B25083256 error
400 B33657578 error
404 B12733087 error
405 B86888981 error
407 B59863074 error
412 B45226850 error
413 B98549278 error
416 B22724156 error
417 B73719677 error
418 B79546632 error
419 B60353936 error
426 B45740188 error
427 B87117960 error
430 B25322413 error
435 B71626726 error
437 016_S_4951 error
438 B43080265 error
439 B64502143 error
443 B81479946 error
444 B48063417 error
451 B46833538 error
452 B62006512 error
453 B13462994 error
454 B75792947 error
456 B12973617 error
457 B58085043 error
458 B16622294 error
459 B78989791 error
463 B27815344 error
469 B85887831 error
470 B42971111 error
472 B88685336 error
475 B87014352 error
477 B45693727 error
479 B27931709 error
487 B79623277 error
490 B31449508 error
491 B26243747 error
492 B46263314 error
494 B73221072 error
495 B39957492 error
497 B91610895 error
498 B77404774 error
509 B66773076 error
511 B46749105 error
512 B20821465 error
514 B65544880 error
518 B21661267 error
520 B68214158 error
523 B36560527 error
526 B85521550 error
529 B37111077 error
531 B20695065 error
532 B79600528 error
533 B64808741 error
535 B59018813 error
536 B50661048 error
537 B60292618 error
538 B62738802 error
539 B52347139 error
544 B94456117 error
550 B53483769 error
552 B60051664 error
553 B83808238 error
556 B10249960 error
563 B54046603 error
564 B21730144 error
566 B17286940 error
567 B90352942 error
572 B15049713 error
573 B34081894 error
574 B25914179 error
575 B62724685 error
576 B72072943 error
584 B48715963 error
587 B42279502 error
590 B47526159 error
595 B38894029 error
596 B16854087 error
598 B20870108 error
603 B51621376 error
604 B45438337 error
608 B77577693 error
610 B55873864 error
614 B71284019 error
615 B53936290 error
620 B69137936 error
627 B74757441 error
628 B86673583 error
629 B90107094 error
630 B48646784 error
631 B41989801 error
632 B70671894 error
635 B21944456 error
636 B98580510 error
643 B31608310 error
647 B48228163 error
648 B71296623 error
649 B60212601 error
650 B39673338 error
654 B69419592 error
655 B62700740 error
657 B47144708 error
660 B61624576 error
664 B68196665 error
666 B86081389 error
668 B22019069 error
671 B20972265 error
672 B21269476 error
673 B53591005 error
674 B38501960 error
675 B93512929 error
676 B98503178 error
677 B45187570 error
678 B22532545 error
679 B21117165 error
683 B27793726 error
685 B60912196 error
686 B78281126 error
688 B52309917 error
689 B11767131 error
690 B35586280 error
695 B10147592 error
696 B84798981 error
697 B41062043 error
698 B15182731 error
701 B14096004 error
705 B37270792 error
707 B22823380 error
710 B18383308 error
718 B13778736 error
719 B97289183 error
722 B28307135 error
727 B17166655 error
730 B65225631 error
731 B25458164 error
732 B19577271 error
733 B74551028 error
737 B78827989 error
739 B30493694 error
740 B33760358 error
741 B55936217 error
748 B26489785 error
749 B90230951 error
753 B45198664 error
754 B40669769 error
763 B76613533 error
765 B88393540 error
770 B35003375 error
775 B55523208 error
781 B27004518 error
782 B72081395 error
783 B27561001 error
784 B77484548 error
788 B11420098 error
789 B63549607 error
791 B66409939 error
796 B87355530 error
799 B84795036 error
802 B43230907 error
804 B46437677 error
805 B61421682 error
806 B63929926 error
807 B28055871 error
809 B45647066 error
810 B82458460 error
811 B13985427 error
816 B75456191 error
824 B65542689 error
825 B38320701 error
826 B65937056 error
827 B97634780 error
828 B49235298 error
832 B66285984 error
833 B24449661 error
843 B75144329 error
856 B48460622 error
858 B16354508 error
859 B68263589 error
860 B78323723 error
863 B47202851 error
865 B49617848 error
874 B56882943 error
877 B63926118 error
879 B71468250 error
881 B59406085 error
882 B11423011 error
883 B17527975 error
891 B48716476 error
899 B71009525 error
900 B82048566 error
904 B27471073 error
905 B24529010 error
906 B67230497 error
909 B40274881 error
912 B94153869 error
913 B84268181 error
914 B27724727 error
918 B20166139 error
921 B13250183 error
923 B42078085 error
924 B93930240 error
927 B55577640 error
929 B45663323 error
930 B44856387 error
932 B65253704 error
933 B40916185 error
936 B73130519 error
939 B78459096 error
941 012_S_6503 error
942 B14810430 error
943 B23100134 error
945 003_S_5154 error
949 B28378466 error
950 B51580985 error
951 B94334752 error
952 B32204053 error
958 B97486876 error
959 B97199792 error
961 B67634825 error
962 B52080056 error
963 B85504951 error
966 B48682338 error
967 B65485360 error
968 B71833825 error
977 B86861838 error
978 B49348519 error
984 B49218213 error
988 B24069948 error
994 B57580428 error
995 B72818039 error
997 B61204908 error
998 B62326693 error
1000 B80615705 error
1001 B73090377 error
1003 B91805128 error
1005 B90421413 error
1008 B32540666 error
1009 B72777285 error
1010 B68320043 error
1012 B54215030 error
1013 B85102524 error
1014 B38099550 error
1015 B32632215 error
1017 B81860791 error
1018 003_S_0981 error
1019 B24487599 error
1023 128_S_0138 error
1024 B84365406 error
1032 B34162617 error
1033 B40077470 error
1037 B92016362 error
1039 B77276631 error
1043 B66484898 error
1046 B95451487 error

1047 B18100327 error
1050 B79652440 error
1052 B50913849 error
1058 B91764226 error
1059 B96597815 error
1060 031_S_2018 error
1061 B11667035 error
1062 B55006637 error
1065 B83599353 error
1066 B25715232 error
1067 B52801561 error
1069 B48227553 error
1077 B97247975 error
1080 B42635533 error
1082 B82078560 error
1086 B30214599 error
1088 B73475423 error
1089 B87363937 error
1095 B26951105 error
1099 B43098693 error
1102 B63792019 error
1106 B24090258 error
1108 B81187857 error
1115 B90575129 error
1125 B65836649 error
1127 B98388895 error
1128 B65781664 error
1130 B17525647 error
1131 B26883230 error
1132 B61130259 error
1134 B82590204 error
1137 B13681621 error
1139 B44794062 error
1141 B46123892 error
1143 B32037155 error
1144 B29314228 error
1146 B26506745 error
1147 B99260348 error
1149 B78516379 error
1153 B34001495 error
1155 B98604009 error
1156 B42756185 error
1159 B32085845 error
1161 B64896348 error
1162 B47152746 error
1163 B39460060 error
1164 003_S_4441 error
1165 022_S_0096 error
1168 B22738484 error
1171 B60059529 error
1172 B42687120 error
1173 B75802324 error
1175 B34728184 error
1177 B37324279 error
1178 B96327266 error
1179 B14990285 error
1180 B13609547 error
1185 B67641382 error
1188 B27252655 error
1192 B49626493 error
1193 B29557489 error
1195 B29230779 error
1196 B65480854 error
1197 B18938225 error
1198 B86714830 error
1199 B81866914 error
1201 B45161116 error
1202 B35803330 error
1204 B29968550 error
1208 003_S_4119 error
1209 B99712573 error
1211 B91508507 error
1212 B40656192 error
1216 B55924369 error
1218 B42878931 error
1219 B51607983 error
1221 B17324595 error
1222 B74512290 error
1224 B33683314 error
1229 B56068547 error
1230 B18779539 error
1231 B76913260 error
1233 B23721474 error
1239 B89710184 error
1240 B80451144 error
1243 B67233410 error
1244 B26323653 error
1250 B97473675 error
1251 B91718720 error
1253 B20992199 error
1261 B36098476 error
1268 B95848984 error
1270 B82596796 error
1274 B98546701 error
1277 B95418012 error
1285 B33013961 error
1286 B52464747 error
1288 B49823273 error
1289 B91735310 error
1292 B47542681 error
1293 B94532847 error
1299 B61910575 error
1306 B30667851 error
1307 B86939254 error
1309 B11032397 error
1311 B30426712 error
1315 B15179550 error
1316 B94125462 error
1317 B86107608 error
1319 B50151967 error
1326 B93655592 error
1331 B52938706 error
1338 B56643481 error
1342 027_S_5083 error
1343 B75795426 error
1344 B57453146 error
1347 B84221821 error
1349 B79258631 error
1353 B60653139 error
1355 130_S_0969 error
1360 B56682994 error
1364 B92612758 error
1372 B95160103 error
1374 B98916876 error
1376 B62909210 error
1377 B35407340 error
1380 B75581038 error
1381 B97004771 error
1382 B77112049 error
1383 B51672774 error
1387 B79068411 error
1388 B93549418 error
1390 B41121864 error
1392 B80753807 error
1393 B16929930 error
1394 B38377120 error
1397 B31980229 error
1398 B12763800 error
1400 B28391147 error
1401 B84081151 error
1403 B93489974 error
1405 B71595411 error
1409 B70201205 error
1413 B12866607 error
1414 B25697655 error
1415 B78726260 error
1417 B34896121 error
1420 B96472148 error
1421 B62252828 error
1423 B64540309 error
1427 B58540900 error
1433 B50491315 error
1438 B43983745 error
1440 B66434514 error
1442 B99649295 error
1444 B75402888 error
1447 B52952375 error
1448 B50885297 error
1449 B71967846 error
1453 B59725042 error
1456 B29978839 error
1460 B11372931 error
1463 B22789552 error
1468 B32916482 error
1469 B12389857 error
1472 B27199671 error
1473 B79522951 error
1474 B75903121 error
1485 B87252406 error
1487 B29568436 error
1488 B98326322 error
1489 B64295256 error
1490 B31289470 error
1494 B88312902 error
1495 B19056515 error
1506 B80606009 error
1515 B14688943 error
1518 B20306888 error
1520 B70778338 error
1521 B46558995 error
1526 B64785541 error
1527 005_S_4168 error
1529 B39716784 error
1531 B55272729 error
1534 B73405873 error
1536 B10326478 error
1539 B38005565 error
1540 B29266685 error
1543 B60752525 error
1544 B12679071 error
1546 B40853335 error
1548 B70453728 error
1552 B36865559 error
1554 B88840257 error
1555 B41570591 error
1557 B71071275 error
1558 098_S_0896 error
1559 B74033374 error
1565 B53703951 error
1566 B42700041 error
1568 B65217177 error
1574 B55634793 error
1576 B15852147 error
1578 B14797911 error
1579 B26067062 error
1580 B20382422 error
1582 B99627197 error
1584 B30680905 error
1586 037_S_0467 error
1589 B14941612 error
1591 B91454779 error
1595 B21413908 error
1596 B20740840 error
1607 032_S_4429 error
1608 B97770680 error
1609 B31236906 error
1612 B79303291 error
1613 B70592438 error
1614 032_S_0214 error
1616 B72497732 error
1620 B18137019 error
1621 B92769298 error
1623 B65190896 error
1624 B49696826 error
1625 B38591673 error
1626 B23241225 error
1629 B17196167 error
1632 B98836822 error
1633 B47782556 error
1636 B12188286 error
1643 B46963927 error
1646 B69422693 error
1654 B58813776 error
1658 B89349522 error
1659 B54454546 error
1663 B94889184 error
1670 B63854498 error
1671 B21715360 error
1676 B34915521 error
1677 073_S_4382 error
1679 B35490090 error
1680 031_S_2233 error
1681 B61399425 error
1682 B22341882 error
1684 B58458644 error
1688 B41986305 error
1689 B25496354 error
1691 B35498652 error
1695 B40415410 error
1696 B49965245 error
1697 B89440803 error
1702 B20901614 error
1705 B41813026 error
1706 B12433306 error
1707 B91602039 error
1708 B99707266 error
1709 B85769522 error
1711 B74028786 error
1715 B75023890 error
1716 B38183382 error
1719 B89250106 error
1722 B28815175 error
1725 B26186843 error
1727 B18640906 error
1728 B43593092 error
1730 B38829455 error
1736 B52222720 error
1737 B98305564 error
1738 B27268860 error
1741 B63644431 error
1748 B59255329 error
1750 B57193995 error
1757 B50531225 error
1764 B40617577 error
1767 B40512051 error
1773 B68035611 error
1775 B20276478 error
1776 B52378038 error
1780 B28140867 error
1783 B82183676 error
1784 B91998097 error
1788 B38875844 error
1790 B10914097 error
1800 B68161988 error
1804 002_S_4746 error
1810 B38850961 error
1811 B63579563 error
1814 B13236125 error
1815 B60356442 error
1819 B59301729 error
1823 B61035571 error
1827 B61357984 error
1828 003_S_4872 error
1829 B76856396 error
1833 B86400831 error
1834 B68699626 error
1835 B10857913 error
1836 B96695454 error
1839 B70271730 error
1847 B37761362 error
1851 B93572213 error
1856 B96528666 error
1860 B11503078 error
1865 B71802624 error
1866 B31766154 error
1867 B11146968 error
1871 B70215732 error
1872 B57443844 error
1873 B80379303 error
1875 B94834405 error
1883 B39696735 error
1886 B47686271 error
1888 B38287758 error
1889 B61383532 error
1890 B19747769 error
1893 B86620520 error
1897 B43337330 error
1898 B24358154 error
1901 B67696841 error
1902 B87555770 error
1909 B10401428 error
1915 B34262112 error
1917 B74316803 error
1920 B90473958 error
1921 B97458633 error
1927 B68961632 error
1929 B20076852 error
1932 B25340270 error
1934 B67726955 error
1939 B67706052 error
1942 B12946233 error
1943 B26723511 error
1946 B94604978 error
1949 B56930575 error
1950 B92178093 error
1951 B43027276 error
1952 B72067015 error
1953 B14596336 error
1957 B64617446 error
1958 B76317562 error
1959 B32164754 error
1963 B15377348 error
1967 B47730813 error
1968 B23245367 error
1971 B93204220 error
1973 B69212532 error
1975 B18365023 error
1976 B18028404 error
1979 B84349936 error
1981 B10983835 error
1982 B72297159 error
1987 B50983255 error
1993 B47523761 error
1995 B73208422 error
1996 027_S_0074 error
2001 B28362183 error
2002 B14181797 error
2005 B26255565 error
2009 B93616881 error
2013 B93935813 error
2014 B42564704 error
2015 B11019874 error
2016 B67318062 error
2017 B39835804 error
2023 B42601168 error
2025 B63504083 error
2026 B88148000 error
2030 B58337839 error
2031 B93746772 error
2033 B10021023 error
2036 B22924665 error
2037 B34977227 error
2038 B65764483 error
2039 B43734338 error
2041 B35375914 error
2042 B92070204 error
2043 B74103058 error
2044 B17510022 error
2045 B58211466 error
2047 B14105201 error
2049 B50551759 error
2050 B64751542 error
2051 B79995588 error
2054 B38594270 error
2058 B51487032 error
2060 B20385550 error
2061 B12695921 error
2062 B26591809 error
2065 B76604861 error
2068 B45660159 error
2069 B71305518 error

2076 B69947521 error
2077 B38475589 error
2081 B94562023 error
2082 B74254198 error
2087 073_S_0089 error
2090 B64097756 error
2092 B97500167 error
2100 B62963368 error
2102 B92584337 error
2103 B11503021 error
2104 B98627375 error
2106 B58761418 error
2107 B54963910 error
2109 B94667740 error
2113 B70977963 error
2115 B96048145 error
2121 B61927724 error
2122 B32840128 error
2123 B83170117 error
2124 B95793592 error
2126 B39857656 error
2127 B33878424 error
2128 B91528620 error
2129 B20847910 error
2132 B46774482 error
2134 B85647756 error
2135 B45096540 error
2137 B54910005 error
2138 B94419915 error
2139 B66320183 error
2143 B21466161 error
2148 B84420603 error
2150 B13374109 error
2153 B10720460 error
2159 B63574447 error
2161 B39307056 error
2162 B96745125 error
2163 B32275111 error
2164 128_S_0135 error
2165 B94858957 error
2171 B85596885 error
2172 B36411607 error
2175 B61519626 error
2176 B76372157 error
2179 B98563970 error
2182 B54236260 error
2188 B86472788 error
2189 B54535370 error
2190 B93984676 error
2191 B80045572 error
2195 B36157092 error
2198 B64090903 error
2200 B76894809 error
2201 B90388733 error
2202 B11675499 error
2204 B16504400 error
2205 B72230976 error
2211 B21995896 error
2213 B68815928 error
2215 B15650883 error
2218 B22915472 error
2222 B81498140 error
2223 B12052564 error
2224 B21418927 error
2226 B53735637 error
2238 B12665123 error
2239 B71148528 error
2242 029_S_4290 error
2245 B35732045 error
2246 027_S_5083 error
2249 B88461717 error
2250 B68313010 error
2252 B66799501 error
2253 B31488023 error
2254 B30314107 error
2256 B39513263 error
2257 B76151033 error
2259 B45479611 error
2261 B87009966 error
2264 B31844937 error
2265 B94299631 error
2268 B33093632 error
2269 B66099533 error
2271 B42089683 error
2272 B74130680 error
2276 B59739128 error
2277 B45524980 error
2278 B42829937 error
2284 B19112277 error
2289 B82619276 error
2291 B84623740 error
2295 B78937910 error
2299 B29925256 error
2300 B19049009 error
2301 B32068627 error
2303 B24718652 error
2304 B83905082 error
2306 B47789385 error
2307 B50559509 error
2308 B11690303 error
2309 B96525960 error
2311 B71570549 error
2312 B15465859 error
2314 B73004172 error
2315 B81820393 error
2316 B26907159 error
2320 B99742660 error
2321 B70375483 error
2322 B18223250 error
2324 B10620498 error
2326 B16766016 error
2329 B98168256 error
2332 B90533314 error
2333 B19543189 error
2337 031_S_0294 error
2338 B60172895 error
2339 B12467828 error
2345 B48290234 error
2348 B33458735 error
2349 019_S_4548 error
2351 137_S_4299 error
2352 B32215094 error
2353 B24697286 error
2355 B17277720 error
2359 B92117437 error
2360 B51457128 error
2368 B42795158 error
2369 B51784602 error
2370 B81507016 error
2372 B52076631 error
2378 B98365812 error
2379 B17969521 error
2381 B95548327 error
2385 B80199293 error
2386 B16465950 error
2387 B39471375 error
2389 B53635552 error
2390 B57449578 error
2394 B41900255 error
2398 B50445541 error
2401 129_S_6244 error
2403 B49648468 error
2407 B93696310 error
2409 B33266332 error
2411 B30209839 error
2412 B36248426 error
2414 B90946769 error
2417 B32619709 error
2419 B68148146 error
2420 B89244116 error
2424 B71468780 error
2425 B86266698 error
2432 B68838534 error
2434 B64946544 error
2437 B14585541 error
2443 B53532713 error
2444 B36426422 error
2446 B10537021 error
2447 B91608562 error
2453 B29094516 error
2455 B34758899 error
2456 B63242775 error
2457 B27894645 error
2467 B65069272 error
2469 B96002968 error
2470 B85039611 error
2471 B46235526 error
2472 B39621183 error
2473 B34422083 error
2476 B50308096 error
2477 B10685731 error
2479 B97609812 error
2481 B35531164 error
2482 B22638115 error
2483 B51354124 error
2484 B20569190 error
2489 B75257826 error
2490 B53176814 error
2491 B84635422 error
2494 B64871749 error
2498 B78678884 error
2499 B34014703 error
2500 B59785426 error
2505 B59006988 error
2508 B61679913 error
2509 B50387921 error
2513 B31204959 error
2519 041_S_5141 error
2523 B92812226 error
2530 B24426946 error
2533 B65811352 error
2534 B77834387 error
2537 B12882829 error
2541 B79733093 error
2545 B80002151 error
2549 B30185597 error
2552 B15592485 error
2553 B24721649 error
2555 B45196570 error
2557 B80859201 error
2559 B24734342 error
2561 B15888246 error
2566 B79745274 error
2568 B98407475 error
2569 B85188531 error
2570 B27070304 error
2572 B44356001 error
2578 B75792519 error
2582 B36672765 error
2585 B61973664 error
2588 B73058077 error
2591 B63494331 error
2598 B36675061 error
2604 B37327773 error
2606 B35649452 error
2612 B69328025 error
2617 B82733217 error
2621 B42174997 error
2624 B29039356 error
2625 B76514729 error
2630 B22490877 error
2636 B42089961 error
2639 B41637670 error
2641 B63400849 error
2645 B44665039 error
2646 B98236420 error
2649 B16363145 error
2658 B78841585 error
2659 B45203917 error
2661 B15281814 error
2662 B73851142 error
2666 B60386677 error
2667 098_S_4050 error
2673 B70819625 error
2678 B71949859 error
2680 B82225703 error
2681 B25862060 error
2682 B91784583 error
2684 B11363523 error
2685 B23336494 error
2686 B12872184 error
2687 B81659748 error
2690 B14760524 error
2691 B36288652 error
2692 B56736918 error
2693 B59212864 error
2694 B97174271 error
2701 033_S_1116 error
2704 B57916887 error
2705 B79735530 error
2708 B66197522 error
2711 B93573612 error
2715 B59813335 error
2716 B46196241 error
2717 B75747013 error
2718 B62936705 error
2719 B63772681 error
2721 B17026456 error
2724 B97099300 error
2725 B14097405 error
2734 B39729905 error
2735 B72801157 error
2738 B41166897 error
2740 B37767548 error
2743 B15131349 error
2744 B96606517 error
2747 B64283410 error
2748 B98410189 error
2750 B35812564 error
2752 B94555722 error
2755 B52685075 error
2757 003_S_5154 error
2760 B41119542 error
2762 B16260011 error
2767 B39105436 error
2770 B98552235 error
2774 B63096609 error
2776 B91492560 error
2777 B77210583 error
2782 B30838002 error
2786 B40275193 error
2787 B34906331 error
2789 B29595580 error
2792 B53475392 error
2793 B99968206 error
2795 B90631856 error
2800 B16835831 error
2806 B91502826 error
2809 B32898236 error
2811 B83042639 error
2815 B86357480 error
2816 B19621685 error
2817 B36088544 error
2820 B22611499 error
2825 B84486548 error
2827 B44965920 error
2828 B98544957 error
2829 B59725472 error
2832 B59432902 error
2845 B78842449 error
2849 B88046625 error
2850 B17578406 error
2853 B64375379 error
2864 B37752358 error
2866 B19406093 error
2868 B78978379 error
2872 B74279359 error
2873 B37623948 error
2874 B13517148 error
2875 B94004321 error
2876 B55454529 error
2882 B70940933 error
2883 B69303938 error
2887 B80200788 error
2888 B40345449 error
2889 B80283338 error
2891 B85820232 error
2892 B36017072 error
2897 B75575937 error
2898 B55794638 error
2899 B63292934 error
2903 B39126905 error
2905 B13108517 error
2913 B74848930 error
2914 B56173091 error
2917 B83965154 error
2918 B44396473 error
2919 B11566884 error
2920 B25040019 error
2921 B85171557 error
2924 B99559355 error
2925 B47337267 error
2926 B27223662 error
2928 B23866208 error
2929 B92304620 error
2931 B58166592 error
2934 B15666253 error
2935 B87727892 error
2937 B18094291 error
2942 B87432496 error
2943 B73116649 error
2945 B11988022 error
2946 B66541723 error
2947 B89421832 error
2948 B19406721 error
2949 B45149828 error
2955 037_S_0467 error
2961 B28491341 error
2967 B35962121 error
2968 B54233103 error
2970 B52972412 error
2973 B64711754 error
2976 B12844724 error
2978 B95158057 error
2983 B45818537 error
2985 B49836294 error
2986 B24346647 error
2988 B74115488 error
2989 B35657575 error
2990 B23088115 error
2992 B37167538 error
2993 B89825074 error
2995 B87853262 error
2997 B91597294 error
2998 B63182089 error
2999 100_S_0035 error
3000 B73835481 error
3001 019_S_4548 error
3003 B16716790 error
3005 B60032303 error
3006 B40614975 error
3010 B56191239 error
3013 098_S_4050 error
3014 018_S_4349 error
3020 052_S_4626 error
3021 B71518326 error
3022 B27311959 error
3023 B60809595 error
3024 B47001784 error
3025 B49499613 error
3026 B66326366 error
3027 B37486138 error
3032 B74786573 error
3033 B59269611 error
3035 B92959535 error
3037 B57186952 error
3039 B30884302 error
3040 B62753997 error
3043 B69606651 error
3044 B37816732 error
3045 B19148571 error
3046 B87319834 error
3047 116_S_4175 error

3053 B10474364 error
3056 B38574136 error
3058 B76342677 error
3061 B48223356 error
3065 B60121794 error
3066 B94953588 error
3071 B44197660 error
3072 B68586050 error
3075 B60115081 error
3078 B70268024 error
3086 B29700097 error
3090 B82229966 error
3097 B32336116 error
3099 B29850204 error
3100 B12612807 error
3101 B71045781 error
3105 B27410963 error
3106 B55191322 error
3107 B65880484 error
3109 B22537724 error
3112 B49085636 error
3115 B97890993 error
3118 B80114324 error
3119 B25997384 error
3120 B86838929 error
3122 B63308634 error
3123 127_S_0112 error
3125 B78548470 error
3126 003_S_2374 error
3128 B76617030 error
3129 B80463433 error
3133 B17190663 error
3141 B49403063 error
3142 B59594943 error
3144 B31055219 error
3145 B10197194 error
3159 B74328072 error
3164 B89474904 error
3166 B13536626 error
3167 B60324791 error
3168 B16069984 error
3169 B63857038 error
3177 B36874638 error
3178 B47309675 error
3179 B65428816 error
3181 B83597636 error
3182 B58336776 error
3183 B18420560 error
3184 B69356373 error
3185 B55695152 error
3187 B43775707 error
3188 B35248925 error
3189 B74952814 error
3197 B20735345 error
3199 B62586246 error
3202 B20893129 error
3203 B89806399 error
3204 B53896153 error
3208 B11959861 error
3212 B94293841 error
3213 B30863221 error
3217 B68642935 error
3225 B62773532 error
3231 B21776776 error
3233 B48427863 error
3237 B33892313 error
3238 B30018087 error
3239 B97237187 error
3241 B59817169 error
3247 B29754630 error
3253 B70258170 error
3255 B36827669 error
3257 B22107459 error
3267 B69334508 error
3268 128_S_0138 error
3270 B80275435 error
3276 B12517369 error
3277 B82893064 error
3278 B41020837 error
3279 B68555845 error
3280 B36269907 error
3281 B13061939 error
3282 B99919345 error
3283 B63672460 error
3284 B89365069 error
3285 B34165160 error
3290 B86558983 error
3291 B87178608 error
3293 B76602272 error
3295 B36851824 error
3296 B25208287 error
3299 B54903425 error
3300 B38169690 error
3301 B49316161 error
3303 B84555965 error
3304 B27997211 error
3305 B81814407 error
3306 B58399839 error
3307 B92956481 error
3309 B35558431 error
3315 B98190358 error
3317 B90615847 error
3319 B85161062 error
3320 B12471287 error
3321 021_S_4419 error
3322 B81910333 error
3323 B90602520 error
3326 B78426584 error
3327 B24821883 error
3329 082_S_4428 error
3332 B46252878 error
3337 B52594935 error
3338 B91694531 error
3342 B38881809 error
3346 B60633058 error
3349 B55823701 error
3352 B32009023 error
3359 128_S_4742 error
3365 B20853557 error
3366 B55075525 error
3367 B99198046 error
3369 B91155391 error
3371 B47422641 error
3372 B16323022 error
3373 B33423959 error
3374 B86670631 error
3376 B27207572 error
3377 010_S_0420 error
3378 B73115956 error
3380 B45224529 error
3382 B62032821 error
3383 B77634679 error
3386 003_S_4441 error
3387 B51864121 error
3388 B85747101 error
3389 B83061155 error
3390 B79416762 error
3393 B58820270 error
3396 B79408897 error
3397 B62547369 error
3399 068_S_2315 error
3400 B93017566 error
3401 B26526428 error
3402 B43777048 error
3403 B91559447 error
3404 B22010788 error
3405 B97558082 error
3409 B67342586 error
3413 B40762821 error
3415 B15462336 error
3418 B89501188 error
3420 B78634631 error
3421 B97060705 error
3424 B93471816 error
3425 B53642146 error
3427 B36872312 error
3428 B27509616 error
3429 B18315542 error
3430 B35702174 error
3432 B82975778 error
3433 153_S_6633 error
3436 B36120546 error
3441 B80549529 error
3444 B98349558 error
3451 B68298398 error
3452 B47510753 error
3454 B21898281 error
3460 B83530314 error
3465 B75510302 error
3470 B54967709 error
3471 B45896055 error
3472 B42489954 error
3473 B87239707 error
3474 B77348896 error
3476 B69824927 error
3477 B74881162 error
3482 B39138938 error
3483 B46168660 error
3494 B52022394 error
3502 B82876784 error
3506 B90728463 error
3510 B53579750 error
3514 B56003269 error
3515 B58085571 error
3516 B55875586 error
3517 B74838689 error
3518 B56067471 error
3521 B22190131 error
3523 B26120055 error
3524 B89687120 error
3528 B34958944 error
3530 B41769231 error
3533 B86457007 error
3535 B94905103 error
3537 B67688308 error
3538 B86308681 error
3541 B14167625 error
3543 B71871950 error
3544 B25720104 error
3548 B39173575 error
3550 B62688262 error
3551 B95187686 error
3553 B12717346 error
3557 B77055578 error
3558 B53368051 error
3564 B93755048 error
3568 B37040621 error
3569 B30427315 error
3572 B47980563 error
3573 127_S_0684 error
3574 B50583162 error
3579 B55360998 error
3581 B90428323 error
3582 B51153424 error
3583 B50559725 error
3587 B59802610 error
3593 B78257272 error
3596 B15923786 error
3597 B80207531 error
3600 B15937978 error
3607 B76061540 error
3610 B51361077 error
3614 B86140687 error
3615 B95442497 error
3619 B99240257 error
3623 B84487456 error
3624 B38878238 error
3626 B27800755 error
3627 B82959487 error
3628 B53131954 error
3629 B70575076 error
3639 B79139339 error
3641 B89680048 error
3642 B21024763 error
3643 B70428371 error
3645 B93065939 error
3646 B83667674 error
3647 010_S_4345 error
3650 B82138495 error
3653 B93997293 error
3656 B75665172 error
3657 B43523165 error
3658 B58037950 error
3660 128_S_0205 error
3661 B15796600 error
3673 B39367823 error
3676 B76238409 error
3677 B23853980 error
3678 B95599705 error
3679 B38730127 error
3680 B69269764 error
3686 B88070690 error
3687 B12654969 error
3691 B82977959 error
3692 109_S_2200 error
3693 B11109399 error
3697 B23547581 error
3698 B14452579 error
3704 B44721907 error
3708 B39683597 error
3719 B25267812 error
3720 B55923123 error
3722 B98581431 error
3723 B83126970 error
3725 B32831808 error
3732 B16554860 error
3733 012_S_6837 error
3735 B77066279 error
3736 B74937941 error
3739 003_S_4872 error
3741 B35212032 error
3743 B52291312 error
3744 B37458200 error
3746 B14453895 error
3747 B19326038 error
3755 B40836038 error
3757 B67735365 error
3758 B45605532 error
3759 B93208850 error
3760 B30378980 error
3763 B97511846 error
3764 B79574171 error
3767 B22336195 error
3768 B76653937 error
3769 B17532967 error
3770 B58292914 error
3777 B46239553 error
3784 B74013423 error
3785 B20994406 error
3787 B85839743 error
3789 B11816003 error
3792 B35646808 error
3798 B22178008 error
3800 B21502063 error
3801 B64527084 error
3802 B74940412 error
3804 B95135869 error
3806 B69187556 error
3808 B72991337 error
3809 B17526081 error
3810 B14463169 error
3811 B50618130 error
3815 B65298306 error
3816 B60812925 error
3817 B93776693 error
3820 B48231640 error
3824 B68453927 error
3828 B79912035 error
3829 B81829341 error
3834 B91806395 error
3835 B13927244 error
3840 B75371544 error
3841 B88725305 error
3842 B32573323 error
3848 B51222558 error
3849 B45034419 error
3850 B13692508 error
3852 B99740505 error
3853 B60405894 error
3854 B57555416 error
3856 B68181096 error
3858 B31112737 error
3860 B80376518 error
3862 003_S_0981 error
3863 B53246798 error
3864 B39194804 error
3865 B71864545 error
3866 B91816804 error
3872 B64405018 error
3873 003_S_4288 error
3875 B41351048 error
3877 B57519014 error
3879 B45948588 error
3880 130_S_5258 error
3881 B56531832 error
3884 B55232102 error
3887 B72923455 error
3889 B76752422 error
3895 006_S_4485 error
3896 B24997068 error
3899 B89510874 error
3900 B81332104 error
3903 B36710735 error
3905 B83411934 error
3915 B40418145 error
3918 B33980160 error
3921 B15793937 error
3928 B27434062 error
3935 B59305662 error
3937 B26918845 error
3938 B80758647 error
3943 005_S_0572 error
3947 B83827519 error
3952 B24417814 error
3954 B38939702 error
3955 B27800596 error
3956 B28766761 error
3959 B47480989 error
3960 B11463763 error
3961 B87925715 error
3964 B19137364 error
3966 B84758313 error
3968 B68184156 error
3969 B48077754 error
3970 B27536313 error
3971 B93008739 error
3972 B20543167 error
3973 B11121557 error
3979 B20179130 error
3983 B79478232 error
3985 B11180089 error
3986 B39256948 error
3989 B39002296 error
3990 B21802565 error
3993 B20192791 error
3996 B95848442 error
4001 B44476099 error
4004 B82358442 error
4006 B82482508 error
4008 B15068192 error
4010 B91751717 error
4012 B29513921 error
4014 B24028620 error
4016 B33515870 error
4023 B63697000 error
4028 B73692409 error
4029 B28346473 error
4031 B42304293 error
4034 B32749420 error
4047 B81134362 error
4050 B44405045 error
4060 B72407244 error

4068 B10594635 error
4072 B38848592 error
4074 B65186366 error
4077 B85693841 error
4078 B69682621 error
4079 B52970639 error
4081 021_S_6978 error
4082 B98230141 error
4089 B28921939 error
4090 B14016331 error
4092 B25703979 error
4093 B98241639 error
4094 B63152407 error
4105 B40067953 error
4106 B63911664 error
4108 B71648555 error
4109 B12163141 error
4115 B80353193 error
4116 B11544718 error
4117 B84614270 error
4118 B89044340 error
4120 B81138926 error
4122 B96481536 error
4123 B47858685 error
4124 B82868543 error
4135 B44826377 error
4136 B17623548 error
4137 B82189482 error
4138 B82533431 error
4141 B34205680 error
4143 B17697191 error
4144 B41586550 error
4145 B42982161 error
4146 B66830066 error
4149 B53424484 error
4151 B92223444 error
4155 B65244102 error
4157 B50166298 error
4158 B95504281 error
4166 041_S_4004 error
4168 B86768925 error
4169 B26375382 error
4173 B62426845 error
4175 B32512144 error
4177 B63496946 error
4181 B10269249 error
4188 B96482424 error
4190 B61707972 error
4192 003_S_0907 error
4194 022_S_0096 error
4202 B25664832 error
4206 B72413884 error
4208 B54060025 error
4211 B98792371 error
4214 B30774029 error
4215 B19255478 error
4218 B59793765 error
4219 B23079355 error
4221 B94342245 error
4223 B42877153 error
4225 B99526771 error
4226 B46505374 error
4227 B75760982 error
4230 B30814745 error
4235 B27346001 error
4236 B87680808 error
4239 B30604839 error
4243 B84578183 error
4247 B60864754 error
4251 B18031978 error
4252 B39578772 error
4253 B87978863 error
4255 B48938351 error
4260 B88655193 error
4261 B45708398 error
4265 B42428900 error
4266 B48133080 error
4272 B18360491 error
4273 B43831069 error
4276 B25582863 error
4277 B77471544 error
4281 B15095361 error
4282 B52568144 error
4284 B70636609 error
4286 B86925797 error
4287 B71955458 error
4288 B96341676 error
4296 B24087881 error
4297 B25943954 error
4300 B53895255 error
4304 B23938303 error
4307 B41474149 error
4308 B99878018 error
4318 B34798911 error
4322 B84557024 error
4330 B28346015 error
4335 B47372783 error
4336 037_S_5222 error
4337 B96372154 error
4338 B58348644 error
4339 B18370983 error
4342 B60209868 error
4343 B90323358 error
4346 B45731810 error
4352 B99137686 error
4355 B92680735 error
4359 B64886630 error
4362 B92211147 error
4370 B36110556 error
4372 B86643156 error
4373 B88108943 error
4374 B68078093 error
4378 B39787877 error
4381 B84923987 error
4384 B22272253 error
4386 B19250041 error
4390 B20368802 error
4392 B72147197 error
4396 B61981093 error
4399 B52726404 error
4402 B44102536 error
4404 B11562001 error
4405 B45512175 error
4406 B76290687 error
4408 B61273772 error
4412 B79712578 error
4416 B69144846 error
4418 B24064818 error
4419 B35156831 error
4421 B88758124 error
4422 B35200955 error
4424 B22924179 error
4425 B93712264 error
4426 B86377265 error
4429 B24709785 error
4430 B16740625 error
4431 B52884715 error
4432 019_S_4548 error
4434 B59837446 error
4440 B18161940 error
4446 B22358364 error
4448 B52432760 error
4451 B73974231 error
4453 B11117241 error
4454 B56580255 error
4455 B21119199 error
4457 B78868439 error
4458 B75838260 error
4461 B81177098 error
4464 B27693117 error
4465 B29096376 error
4466 B46763491 error
4467 B21135157 error
4471 B28764786 error
4472 B32348295 error
4474 016_S_2007 error
4476 B11425461 error
4478 B41544101 error
4479 B97002341 error
4484 B64774570 error
4485 B70727460 error
4489 B18148080 error
4491 B47787974 error
4492 B46883668 error
4495 B64942588 error
4496 B81476839 error
4499 B16771817 error
4503 B69406331 error
4508 B97414423 error
4509 003_S_6158 error
4512 B83608580 error
4515 B57413622 error
4516 B49761823 error
4518 B83064974 error
4519 B52467476 error
4520 B18410994 error
4526 B63809133 error
4529 B28930602 error
4536 B12506639 error
4539 B85110148 error
4540 B98485983 error
4545 B26665010 error
4546 B73136123 error
4547 B69937200 error
4550 B77296366 error
4557 B15360463 error
4562 B78371570 error
4571 018_S_4597 error
4572 B92299514 error
4576 B46080916 error
4579 B92640934 error
4580 B28015045 error
4582 B15554656 error
4584 B83741347 error
4585 B43875800 error
4586 B56581478 error
4602 B49955065 error
4606 041_S_4060 error
4609 B14576587 error
4610 B20265962 error
4613 B32736709 error
4617 B70182709 error
4620 B30005681 error
4622 B71093520 error
4623 B29195732 error
4624 B56017111 error
4628 B23148890 error
4630 B16597969 error
4635 B64549589 error
4637 B28645650 error
4640 B96407910 error
4643 B97850935 error
4645 B11187381 error
4647 B19535736 error
4649 B17083554 error
4650 B81466154 error
4651 B52426028 error
4653 B11465265 error
4655 B57638728 error
4659 B63976618 error
4662 B61690634 error
4665 B55734435 error
4673 B41396276 error
4679 B58233740 error
4680 B88983059 error
4683 B59184079 error
4684 B99218415 error
4685 B72687910 error
4692 B94765964 error
4693 B62133624 error
4694 B80264657 error
4695 B82601406 error
4696 B59951698 error
4697 B77447068 error
4698 053_S_4557 error
4699 B27260967 error
4701 B64318343 error
4705 B11613842 error
4710 B69734579 error
4713 B32272665 error
4721 B86041722 error
4724 B14058997 error
4725 B67537423 error
4726 B92948902 error
4729 B27916756 error
4730 B16130565 error
4733 B16115092 error
4734 B20795334 error
4735 B31735089 error
4736 B52117843 error
4737 B93292576 error
4738 B83338272 error
4739 B42494418 error
4741 B47702026 error
4744 B29934345 error
4745 B84010038 error
4747 B64032906 error
4750 127_S_0684 error
4751 B11255389 error
4753 B71073933 error
4754 B27796995 error
4758 B83034058 error
4762 B34914499 error
4764 B40976683 error
4765 006_S_0498 error
4766 B37722093 error
4769 B80411637 error
4773 B25995285 error
4776 B62090728 error
4778 B65321443 error
4780 B18444559 error
4781 B36209796 error
4783 B84978461 error
4788 B41127960 error
4790 B77976687 error
4791 B30084742 error
4794 B26819938 error
4796 B75642651 error
4799 B61374765 error
4803 B66921348 error
4805 B99249676 error
4806 B68388971 error
4811 B71524655 error
4813 B33224037 error
4814 B78227730 error
4817 B50993766 error
4821 B66570373 error
4825 B67189432 error
4826 B51766379 error
4827 B53409365 error
4831 B72121693 error
4832 B10955942 error
4834 B77293872 error
4835 B92202894 error
4837 B27779140 error
4838 B46561170 error
4839 B11589483 error
4842 B86696362 error
4845 B57392869 error
4849 B94218969 error
4850 B19720738 error
4853 B81515073 error
4854 B89810417 error
4855 B18678187 error
4860 B82512245 error
4861 B81636257 error
4864 B33360523 error
4865 B85645981 error
4867 B23675190 error
4871 B64097257 error
4878 B68754040 error
4881 B62834354 error
4892 B31114755 error
4896 003_S_4350 error
4901 B24527576 error
4902 B91021698 error
4906 B66420567 error
4907 B65920861 error
4909 B58660452 error
4910 B47425404 error
4919 B52970019 error
4921 B43686483 error
4922 B71136115 error
4924 022_S_0096 error
4925 B29461336 error
4928 B94301823 error
4929 B88733688 error
4934 094_S_4503 error
4936 B31825780 error
4939 005_S_0448 error
4944 B85846976 error
4946 B59944921 error
4947 B13020871 error
4949 B63895006 error
4952 B77596233 error
4953 098_S_4095 error
4959 B81358849 error
4960 B87951111 error
4962 B53275632 error
4964 B42066528 error
4971 B58515672 error
4974 137_S_4587 error
4975 021_S_4419 error
4976 B37655279 error
4981 B75637489 error
4985 B40026582 error
4989 B81930587 error
4990 B45752110 error
4992 B66220286 error
4995 B71009750 error
4997 B18355398 error
4998 B68573881 error
5004 B22596006 error
5005 B96985721 error
5006 B20029614 error
5007 B90132670 error
5011 B25759653 error
5012 B19730380 error
5017 B32190485 error
5020 B67220429 error
5025 B89048078 error
5030 B98657545 error
5031 B18230894 error
5032 305_S_6188 error
5033 B89975810 error
5037 B11053374 error
5042 B49568740 error
5045 B67153070 error
5047 B23315157 error
5048 094_S_4649 error
5050 B50433022 error
5052 B86632894 error
5054 B41836198 error
5055 B59458010 error
5058 B80082916 error
5062 B60783767 error
5063 B19473229 error
5064 B76285869 error
5067 B21422472 error
5069 B80765191 error
5071 B33206535 error
5073 B59828989 error
5074 B39504242 error
5077 B65723587 error
5079 B33355054 error
5082 B25242037 error
5083 B18168309 error
5084 B14278268 error
5085 B45957303 error
5087 B81592156 error
5088 B50947879 error
5089 B38729704 error
5093 B67031268 error

5095 B74858321 error
5099 B18371517 error
5100 B37464403 error
5101 B77123736 error
5106 B11963311 error
5108 053_S_4557 error
5109 B40298974 error
5110 B97240044 error
5111 B76202643 error
5112 B62102097 error
5113 B75082659 error
5115 B62326221 error
5120 B46595298 error
5122 B73283951 error
5124 B41880122 error
5131 B25986473 error
5132 B58842024 error
5133 B83473676 error
5136 B14057870 error
5139 B80202813 error
5140 B14331746 error
5141 B47511909 error
5147 B37105702 error
5154 B77262465 error
5155 B47317519 error
5157 B25726927 error
5163 B28164897 error
5165 B70299785 error
5168 B77211272 error
5172 B60721999 error
5175 B62565687 error
5176 B25603360 error
5180 B29038688 error
5181 B68102365 error
5182 B60701396 error
5183 B19496904 error
5188 B43571699 error
5191 B55104276 error
5192 129_S_4220 error
5193 B61235862 error
5200 B49731201 error
5201 B31548493 error
5202 B10149443 error
5206 B89108723 error
5207 B63580375 error
5215 B50610981 error
5219 B12806498 error
5220 B18983005 error
5222 B47031356 error
5223 B75089005 error
5225 B89134973 error
5226 B28198903 error
5227 B33876826 error
5232 B89979828 error
5234 B14057815 error
5235 B81701807 error
5236 B65395310 error
5237 B33237056 error
5239 B30655404 error
5241 B17062781 error
5242 B37784849 error
5245 B58234331 error
5249 B44142422 error
5251 005_S_0572 error
5252 B39678395 error
5254 B10263380 error
5257 B34937897 error
5260 B56341436 error
5262 B15395707 error
5267 B74460424 error
5269 B94269930 error
5270 B81047025 error
5271 B58321877 error
5274 B63045648 error
5275 B43491712 error
5278 B86871153 error
5281 003_S_4872 error
5282 B45089018 error
5288 153_S_6694 error
5289 B82518057 error
5292 003_S_0908 error
5299 B80300958 error
5301 B31934006 error
5302 B30913498 error
5305 B26063966 error
5306 B99469159 error
5310 B67349512 error
5311 B43907331 error
5313 B93458335 error
5317 B35296023 error
5318 B81781832 error
5319 B29249116 error
5320 B81521057 error
5323 B17579659 error
5328 B70354222 error
5331 B30341223 error
5332 B31153380 error
5335 B38415337 error
5337 B78296947 error
5341 B16836732 error
5343 B54851816 error
5344 B77896466 error
5347 B94196420 error
5348 B64371755 error
5352 B31361733 error
5354 B30492110 error
5355 B45368932 error
5358 B38482851 error
5359 B78818167 error
5363 B52501510 error
5364 B32291114 error
5367 B73907078 error
5368 B18079988 error
5369 B11089689 error
5370 B93372821 error
5372 B10280784 error
5373 B50108000 error
5374 B89723210 error
5377 B10372262 error
5386 B61212466 error
5388 B46567752 error
5391 B46371252 error
5392 B89039707 error
5393 B35329362 error
5395 B41172504 error
5398 B36935083 error
5403 B57705421 error
5404 B21317798 error
5405 B38152644 error
5406 B20611141 error
5408 B20450614 error
5409 B46394464 error
5411 B33452817 error
5413 B18073217 error
5417 B89285031 error
5419 B67148729 error
5420 B40796597 error
5423 027_S_4966 error
5424 B20606664 error
5425 B10733385 error
5427 B20640601 error
5428 003_S_1122 error
5429 B54283837 error
5430 B44898014 error
5432 B37033373 error
5434 B19297404 error
5435 B78137905 error
5437 B41281001 error
5441 B43318386 error
5444 B17368079 error
5447 B88572191 error
5448 B32762804 error
5451 B36047234 error
5453 B65939345 error
5456 B23462581 error
5461 B26357401 error
5464 003_S_4900 error
5465 B35460675 error
5468 B22409181 error
5469 B95641512 error
5470 B25885161 error
5475 B42377714 error
5477 130_S_0285 error
5478 B78026248 error
5483 B66591418 error
5485 B76226417 error
5488 B59603878 error
5490 B58044111 error
5491 B57081773 error
5492 B65366964 error
5493 B18782412 error
5495 B19470960 error
5498 B98042931 error
5499 B19855783 error
5501 B21786100 error
5504 B91238660 error
5505 B23469821 error
5506 B95446891 error
5507 B78334488 error
5511 B87843858 error
5512 B59455596 error
5514 B12876680 error
5516 B78890559 error
5517 B22073914 error
5518 B21004391 error
5521 B40918968 error
5524 B51616823 error
5525 B19619598 error
5532 B28007132 error
5536 B34958971 error
5541 B36795722 error
5542 B98403873 error
5543 B34894890 error
5544 B85848590 error
5546 B31637376 error
5548 B51182719 error
5550 B20941636 error
5554 B13047951 error
5556 B75514976 error
5558 B77506242 error
5560 B14764879 error
5562 B61444803 error
5574 B41098801 error
5577 B54951935 error
5578 B92664142 error
5580 B77320324 error
5581 B64348082 error
5582 B44744435 error
5585 B66116644 error
5591 B65923973 error
5592 B30692922 error
5593 B11913770 error
5597 B30023693 error
5598 B20715085 error
5600 B13223295 error
5606 B35129129 error
5607 B91401207 error
5610 B81394673 error
5612 B81785840 error
5618 B78281491 error
5620 B55874560 error
5622 B60814649 error
5624 B36431337 error
5629 B77749818 error
5632 B49771486 error
5641 B71466570 error
5644 B96852955 error
5646 B96355440 error
5647 B26779274 error
5653 B42899029 error
5654 B53468148 error
5657 B34705870 error
5658 B55142121 error
5659 B39327685 error
5662 B27908922 error
5664 B70085115 error
5665 B57424184 error
5666 B10358073 error
5668 B84020081 error
5672 B31800023 error
5673 B74585138 error
5676 128_S_0138 error
5677 B81916291 error
5679 B61470787 error
5680 B65839712 error
5681 B79495699 error
5685 B96280783 error
5689 B65796570 error
5691 B15255438 error
5693 B36038200 error
5694 B93537834 error
5695 B10333421 error
5698 B87611548 error
5699 B15510679 error
5700 B27235709 error
5702 B40395568 error
5705 B58793817 error
5706 B24617122 error
5707 B58812698 error
5710 B77567880 error
5711 B40502570 error
5714 B91535619 error
5715 B53265652 error
5717 B70741446 error
5718 B81279688 error
5719 B57257925 error
5720 B81513646 error
5722 B85249463 error
5723 B30167396 error
5724 B74072762 error
5727 127_S_0684 error
5729 B44056524 error
5731 B35124406 error
5733 B66250604 error
5736 127_S_0684 error
5737 B56607192 error
5739 B38977223 error
5740 B52789149 error
5742 B28506630 error
5744 B72973783 error
5745 B76007298 error
5748 B47078530 error
5751 B17173791 error
5753 130_S_4352 error
5756 B66300512 error
5757 B36702787 error
5758 B48626496 error
5760 B52807897 error
5762 B99501460 error
5763 B29474930 error
5765 B92834432 error
5766 B12416927 error
5769 B19552408 error
5771 B55317521 error
5777 B44537271 error
5778 B68784565 error
5789 B23841379 error
5790 B13462431 error
5791 B65692391 error
5792 B64214045 error
5795 B33822549 error
5797 B39325315 error
5799 B29408644 error
5800 B76057859 error
5801 B15185618 error
5812 B98593191 error
5814 B29640054 error
5815 B84949980 error
5821 B25875561 error
5822 B98608007 error
5826 B32746345 error
5827 B16944934 error
5829 B74253525 error
5831 B85996383 error
5834 B62964339 error
5837 B81873145 error
5842 B99171607 error
5844 B81067788 error
5849 B30737351 error
5851 B85701534 error
5852 B35101849 error
5853 B16021907 error
5855 B53433916 error
5856 B88914950 error
5859 B31291646 error
5860 B34688438 error
5862 B37821003 error
5864 B52992223 error
5865 B70639637 error
5869 B87170224 error
5870 B53484606 error
5873 B96573126 error
5875 094_S_4630 error
5878 B30899631 error
5880 B57424551 error
5882 B87323894 error
5883 B52523828 error
5884 B77935552 error
5885 B49399605 error
5890 B63878354 error
5891 B77660760 error
5894 B79647904 error
5896 B74434512 error
5902 B46838391 error
5903 003_S_6264 error
5908 B52764091 error
5911 B72532048 error
5912 B27881918 error
5915 B81177203 error
5918 B49477379 error
5920 B45947840 error
5921 B40455987 error
5923 B10524918 error
5924 032_S_1169 error
5926 B79581261 error
5928 B17675117 error
5929 B30576600 error
5930 B69101845 error
5931 B91082782 error
5932 003_S_5130 error
5933 B71116809 error
5935 B13046794 error
5937 B25259827 error
5941 B68190352 error
5942 B40135516 error
5943 B70657230 error
5944 B35933079 error
5947 B40651123 error
5948 B23768634 error
5949 B34794040 error
5951 B32558952 error
5954 B27134181 error
5958 B37619742 error
5959 B65899976 error
5961 B23572339 error
5962 B20911400 error
5963 B14100602 error
5964 B69627688 error
5969 B77869916 error
5971 B63979411 error
5974 B23481070 error
5975 B14642664 error
5976 B87999959 error
5977 B67935956 error
5981 B38295669 error
5983 B32525178 error
5984 B72393249 error
5986 B65333204 error
5992 B69089419 error
5994 B18724304 error
5996 B80257265 error
5997 B13848675 error
5999 B93553910 error

6003 B78782605 error
6009 B37019413 error
6010 B36036790 error
6015 B47790811 error
6016 B50072721 error
6017 B76309364 error
6021 B62579289 error
6024 B48309631 error
6027 B24483454 error
6033 B17648113 error
6034 B35818998 error
6035 B55593099 error
6039 B36976155 error
6049 B64751382 error
6053 B67131157 error
6055 B98737188 error
6056 B25735560 error
6057 B77849321 error
6063 B90313419 error
6071 B27040996 error
6072 B55055889 error
6074 B85053420 error
6080 B60904865 error
6082 B36001244 error
6083 B73677676 error
6085 B21494740 error
6092 141_S_4426 error
6094 002_S_4225 error
6095 B20093346 error
6097 B92872041 error
6098 B82289687 error
6101 153_S_6679 error
6103 B30196143 error
6104 B15268431 error
6105 B99586844 error
6106 B82492086 error
6112 B71728664 error
6115 B11171441 error
6121 B36914973 error
6122 B85732666 error
6123 B51940871 error
6126 B35535582 error
6131 B23302827 error
6132 B38433155 error
6134 B45452649 error
6135 B89972311 error
6136 B25747608 error
6137 B60918084 error
6140 B90564809 error
6143 B15196340 error
6144 B94779189 error
6147 B68277314 error
6148 B92129068 error
6149 B19586590 error
6150 B57400472 error
6155 B27369090 error
6159 B65033615 error
6161 B42034596 error
6162 B23006749 error
6170 B86321401 error
6173 B39998888 error
6178 B90462001 error
6179 B20533434 error
6184 B26272209 error
6188 B73221381 error
6192 B44289280 error
6193 B82545588 error
6200 B42723441 error
6201 B42157834 error
6204 B16119761 error
6205 B74723990 error
6206 B56023626 error
6211 B70107107 error
6212 B34668923 error
6214 B96996793 error
6216 B35192088 error
6220 B34372081 error
6221 B91464703 error
6222 B95216651 error
6225 003_S_4900 error
6226 B32177153 error
6230 B60743836 error
6232 B86599316 error
6237 B51291443 error
6238 B89841382 error
6241 B82168489 error
6256 B22070251 error
6257 B55274513 error
6258 B87985033 error
6259 B28486987 error
6264 B80844143 error
6265 B95192708 error
6269 B60808720 error
6273 016_S_4952 error
6275 B42263041 error
6276 B66915174 error
6278 B42602967 error
6279 B87415325 error
6281 B69960776 error
6282 B96620244 error
6288 B33205159 error
6289 B72189298 error
6290 B55031670 error
6291 B63228477 error
6292 B69415584 error
6295 005_S_6393 error
6297 B46015263 error
6298 B45707843 error
6299 B78713131 error
6300 B52948458 error
6302 B47179897 error
6304 B16694591 error
6305 B22485102 error
6306 B98920162 error
6308 B47646571 error
6309 B42014841 error
6314 B70121703 error
6319 B43236327 error
6320 B99822982 error
6322 B61076511 error
6323 B42389173 error
6330 016_S_2007 error
6331 B54473014 error
6333 B25182876 error
6336 B85323928 error
6337 B50469664 error
6339 B34760850 error
6342 B96025663 error
6344 B82896717 error
6345 B78914856 error
6346 B18177695 error
6348 B62050242 error
6356 B73199908 error
6358 B60675832 error
6362 B13910425 error
6363 B95693340 error
6365 B51940669 error
6367 B83724042 error
6373 B11078413 error
6378 B67322499 error
6379 B73840142 error
6381 B46264630 error
6385 B70495592 error
6389 B69590601 error
6396 B41880926 error
6397 B54278137 error
6401 B33384252 error
6404 B98888703 error
6409 B82757524 error
6412 B22647154 error
6420 B13500590 error
6421 B33117611 error
6423 B62537586 error
6426 B81850673 error
6428 B58933795 error
6429 B37464662 error
6431 B78993277 error
6434 B82436811 error
6435 B49518135 error
6438 B64994538 error
6442 B26851047 error
6446 B36172869 error
6447 B31499958 error
6451 B34426408 error
6454 B44346102 error
6455 B46674094 error
6456 B94327305 error
6462 B85495608 error
6465 B59688985 error
6466 B81165490 error
6467 130_S_5175 error
6470 B58967315 error
6472 B79310314 error
6476 B21553880 error
6482 B55809715 error
6485 B41871024 error
6492 B62100905 error
6497 B59748357 error
6500 B48007138 error
6503 B21693941 error
6506 B35394052 error
6507 B20794896 error
6513 B57851368 error
6515 B81291856 error
6517 B39000729 error
6520 B73721444 error
6523 B58122644 error
6525 B34534025 error
6526 B11668390 error
6528 B68660228 error
6530 B46180956 error
6532 B40890583 error
6535 B93849533 error
6537 B90734468 error
6540 B86918860 error
6541 B68194290 error
6542 006_S_4346 error
6544 B23745323 error
6546 B62287364 error
6549 B95987895 error
6552 B23342457 error
6556 B43432680 error
6560 B47381496 error
6561 B26049431 error
6562 B63204009 error
6564 B96876952 error
6568 B91942633 error
6570 B89210112 error
6578 B89574482 error
6580 B23664984 error
6582 B10495310 error
6583 B79788073 error
6585 B55990847 error
6586 B20156716 error
6588 B72044811 error
6589 B55032356 error
6592 B51748476 error
6595 B15651845 error
6602 B17665348 error
6603 B19579079 error
6605 B68536706 error
6607 B96827915 error
6611 B25099440 error
6612 B60141160 error
6613 B55313153 error
6615 B13335140 error
6617 B23529721 error
6618 B26287942 error
6620 B55710108 error
6621 B74416453 error
6623 B63036430 error
6624 B31507306 error
6627 B51389150 error
6629 B28965589 error
6630 B97734465 error
6631 B92621962 error
6632 B26827161 error
6633 B72899408 error
6636 141_S_4711 error
6639 B44579029 error
6644 037_S_5126 error
6645 B50386583 error
6647 B88611242 error
6649 B55665997 error
6650 B29857153 error
6652 B94797131 error
6653 B87158619 error
6656 B46444279 error
6661 B99702303 error
6662 B19193413 error
6663 B58581368 error
6664 B75607359 error
6667 B87002508 error
6668 B24603396 error
6674 B84398559 error
6678 B59305102 error
6679 021_S_5177 error
6680 B82189453 error
6687 B59991838 error
6688 B27932553 error
6690 B40169438 error
6692 B14305912 error
6695 B11927526 error
6698 B48348292 error
6700 B64709336 error
6702 B61742916 error
6704 B80108803 error
6708 B93805512 error
6710 B15626425 error
6711 B87248772 error
6712 B17576894 error
6718 B79652995 error
6720 B39909008 error
6721 B75780376 error
6725 B17032651 error
6728 B96591166 error
6729 B12745317 error
6730 B79168240 error
6731 B17965690 error
6732 B49972637 error
6734 B53386856 error
6735 B50814078 error
6736 B40837681 error
6737 B86805784 error
6738 031_S_0618 error
6740 B55187760 error
6743 041_S_4041 error
6744 B11769839 error
6745 B62400264 error
6753 B49392419 error
6755 B84343992 error
6756 B40176106 error
6757 B65275512 error
6758 B27705327 error
6766 B45880138 error
6767 B23150895 error
6768 B78902586 error
6769 B96955329 error
6771 B69336412 error
6773 B77299420 error
6775 B26502129 error
6777 B42283573 error
6779 B98005010 error
6781 B78925846 error
6785 B63539433 error
6791 B16024449 error
6793 B73406605 error
6795 B83440996 error
6798 B91382794 error
6801 B86239362 error
6805 B31897821 error
6806 B57747669 error
6808 B43398760 error
6811 B40045949 error
6812 B97689089 error
6815 B91268180 error
6818 B65800013 error
6819 B59870866 error
6820 B15072730 error
6822 B88558364 error
6824 B60849461 error
6825 B84578079 error
6826 B75031769 error
6834 B28466114 error
6835 B80339776 error
6838 B89936971 error
6844 B36659277 error
6845 B37906955 error
6846 B16918714 error
6853 B73436806 error
6855 B25194929 error
6857 B80300678 error
6858 B44775622 error
6859 B61854708 error
6860 B48685818 error
6863 B31598693 error
6875 B68380162 error
6877 B75618242 error
6878 B82469848 error
6881 B72332785 error
6885 B64092619 error
6886 B64520355 error
6888 B10018169 error
6889 B68575801 error
6890 B29404062 error
6892 B31020303 error
6893 B62047133 error
6896 B89964058 error
6898 B55707440 error
6905 B85849363 error
6907 B72540951 error
6909 B79467509 error
6910 B37057082 error
6916 B90814536 error
6918 B71477452 error
6921 B71103035 error
6924 B35900517 error
6927 B15965706 error
6930 B77985866 error
6936 073_S_4382 error
6937 B50899558 error
6939 B89454594 error
6941 B60265124 error
6946 B71246512 error
6949 B95079490 error
6954 B66837302 error
6956 B18591728 error
6961 057_S_5199 error
6964 B48668844 error
6966 B60612374 error
6971 B13070698 error
6975 B83826289 error
6977 B86810640 error
6980 B99987993 error
6983 B85264395 error
6984 B52069245 error
6985 B59885622 error
6986 B24537100 error
6987 B92895774 error
6988 B93763582 error
6990 B60667294 error
6992 B22768832 error
6995 B83544197 error
6999 B35168960 error
7000 B74866217 error
7001 B99747327 error
7006 B12432695 error
7007 B84004249 error
7010 B55763896 error
7015 B97758917 error
7020 B57561500 error

7021 B75594674 error
7022 B58902381 error
7025 B15773811 error
7031 B43342955 error
7036 B53006953 error
7038 B84753839 error
7043 B14442341 error
7044 B95334005 error
7047 B17522168 error
7050 B85301718 error
7053 B47149385 error
7054 B36482595 error
7057 B37315445 error
7061 B91484392 error
7063 B87384193 error
7066 B83944186 error
7071 B76135087 error
7073 B47561468 error
7074 B84665222 error
7075 B32966350 error
7077 B24361828 error
7079 B55797169 error
7080 B75018078 error
7081 B81179650 error
7082 B90077295 error
7084 B32658386 error
7091 B91654122 error
7092 B69529107 error
7093 B45863159 error
7095 082_S_4090 error
7098 B45052966 error
7099 018_S_4889 error
7102 B94823120 error
7104 B21161221 error
7107 B18346832 error
7108 B16252289 error
7115 B28268052 error
7117 B44477629 error
7126 B94548172 error
7128 B86175192 error
7130 B79634982 error
7133 B76737750 error
7135 B67104879 error
7136 B14313660 error
7138 B10093965 error
7139 B20610494 error
7141 B51911152 error
7153 B36179545 error
7156 B91772180 error
7157 B99475122 error
7158 B16894160 error
7159 B52187746 error
7162 B88359321 error
7163 941_S_4255 error
7164 B34484478 error
7170 B79119049 error
7183 B29958379 error
7185 B13519855 error
7188 B36008750 error
7193 B84883169 error
7196 007_S_4387 error
7197 B71007977 error
7198 B14879518 error
7199 B62112170 error
7202 B94741450 error
7205 B30733334 error
7207 B74380183 error
7208 B49903736 error
7209 B67963915 error
7218 B68929738 error
7223 B51560785 error
7224 B39911058 error
7225 B44391959 error
7228 B40329410 error
7230 B82315070 error
7231 B94959090 error
7238 B44340580 error
7239 B37468865 error
7241 B60419524 error
7242 B21779703 error
7244 B18480592 error
7246 B84007524 error
7249 B89000856 error
7253 B61348624 error
7254 B45261803 error
7257 B85805569 error
7258 B35222003 error
7262 B41271333 error
7265 B75405514 error
7267 B55662221 error
7276 B40779406 error
7277 B56307985 error
7279 B81274971 error
7280 B65232320 error
7281 B38737635 error
7282 B51152248 error
7283 B90463412 error
7287 B72226458 error
7289 B51285673 error
7290 B97479835 error
7294 003_S_5130 error
7297 B37900172 error
7298 B62531814 error
7300 B85481971 error
7301 B49743819 error
7302 B21758859 error
7305 B48204000 error
7308 B35137198 error
7311 B41375180 error
7314 B89248380 error
7317 B89686766 error
7322 B65639025 error
7324 B80254217 error
7325 B65276521 error
7329 B76467611 error
7331 B35244012 error
7332 B17008025 error
7333 B71444080 error
7335 B35104901 error
7336 B21144269 error
7338 B35820897 error
7339 B47149165 error
7340 B64656714 error
7342 B45794973 error
7343 B78191768 error
7344 B84990948 error
7348 B38159290 error
7351 B62802114 error
7352 B58582904 error
7353 B37709565 error
7354 B32240423 error
7355 B34524774 error
7358 035_S_0555 error
7362 B30864110 error
7365 B60345282 error
7367 B66155156 error
7370 B35596292 error
7372 B18256436 error
7374 B81360966 error
7376 B79931772 error
7378 B39020080 error
7381 B81775109 error
7383 B52730035 error
7384 B99119845 error
7385 B20930557 error
7389 B88254478 error
7390 B57073009 error
7391 B71112502 error
7393 B83317686 error
7395 B70293013 error
7396 B64160267 error
7397 B99411315 error
7398 B11775965 error
7399 128_S_4653 error
7401 B52333851 error
7402 B13433815 error
7404 B65470750 error
7405 B18393836 error
7406 B31490758 error
7407 B24581726 error
7408 B73163819 error
7409 B87758961 error
7414 B42344811 error
7415 B55137558 error
7419 B39718950 error
7428 B88032799 error
7434 B14159885 error
7437 003_S_6644 error
7441 B11328039 error
7442 019_S_4548 error
7443 B67473102 error
7449 B77891191 error
7450 B17670239 error
7453 B90584402 error
7455 B17469249 error
7456 B37761225 error
7457 B45504529 error
7458 B17095928 error
7461 B30383900 error
7462 B93896493 error
7464 127_S_0259 error
7466 B49023098 error
7467 B54310275 error
7468 B19258182 error
7469 B72550059 error
7470 B25696800 error
7474 B50464736 error
7482 B62000953 error
7483 B18223311 error
7486 B16736935 error
7487 B29248204 error
7488 B40345477 error

In [21]:
mri_meta[mri_meta.Phase == 'ADNI GO'].Type.value_counts()

Processed    1192
Original      940
Name: Type, dtype: int64

In [22]:
pet_mri_tab.shape

(7490, 26)

In [23]:
pet_mri_tab = pet_mri_tab[pet_mri_tab['MRI_Age'].notna()]

In [24]:
pet_mri_tab = pet_mri_tab[pet_mri_tab['Age']>0]
pet_mri_tab.reset_index(drop=True, inplace = True)

In [25]:
pet_mri_tab = pet_mri_tab[pet_mri_tab['MRI_Type'] == 'Processed']
pet_mri_tab.reset_index(drop=True, inplace = True)

In [27]:
if (pet_mri_tab['Subject.ID'] == pet_mri_tab['MRI_subID']).all():
    print("✅ All Subject.ID values match MRI_subID.")
else:
    print("❌ There are mismatches between Subject.ID and MRI_subID.")

✅ All Subject.ID values match MRI_subID.

In [28]:
pet_mri_tab.shape

(3716, 26)

In [29]:
pet_mri_tab.Phase.value_counts()

ADNI 2     1807
ADNI GO     248
Name: Phase, dtype: int64

In [30]:
pet_mri_tab.Project.value_counts()

ADNI    2055
A4      1661
Name: Project, dtype: int64

In [31]:
pet_mri_tab

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Study.Date,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_studydate,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH
0,B59563700,A4,NaN,M,83.9,LEARN amyloidNE,SCV2,1/01/2016,84.4,PET,Florbetapir <- MNI_3DBRAIN_C),NaN,I1323673,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B59563700,MRI,LEARN amyloidNE,84.0,SCV4,1/01/2016,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1384728,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
1,023_S_4115,ADNI,ADNI 2,M,84.9,LMCI,v21,9/30/2013,69.7,PET,"AV45 Co-registered, Averaged <- PET Brain AV_4...",SIEMENS,I393755,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,023_S_4115,MRI,LMCI,69.7,v21,9/30/2013,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I398283,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
2,032_S_4429,ADNI,ADNI 2,M,75.7,CN,v21,1/22/2014,79.2,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I413047,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,032_S_4429,MRI,CN,79.2,v21,1/21/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I416035,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3,B45524671,A4,NaN,M,71.4,amyloidE,SCV2,1/01/2016,82.5,PET,Florbetapir <- PET Scan,NaN,I1411194,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B45524671,MRI,amyloidE,82.6,SCV4,1/01/2016,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1364073,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4,B14220479,A4,NaN,F,0.0,LEARN amyloidNE,SCV2,1/01/2016,71.8,PET,Florbetapir <- PET Scan,NaN,I1411241,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B14220479,MRI,LEARN amyloidNE,71.0,SCV4,1/01/2016,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1384417,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3711,067_S_0056,ADNI,ADNI 2,F,76.7,CN,v31,1/07/2015,78.9,PET,"AV45 Co-registered, Averaged <- AV45_Dyn_4x5mi...",SIEMENS,I468830,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,067_S_0056,MRI,CN,78.8,v31,12/15/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I468856,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3712,005_S_0553,ADNI,ADNI GO,M,65.3,CN,m48,12/15/2010,89.3,PET,"AV45 Co-registered, Averaged <- 20 min 3D AV45...",Siemens/CTI,I209032,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,005_S_0553,MRI,CN,89.2,m48,10/13/2010,MT1; GradWarp; N3m <- MP-RAGE REPEAT,GE MEDICAL SYSTEMS,Processed,I322397,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3713,006_S_4153,ADNI,ADNI 2,M,72.1,AD,v21,9/20/2013,81.5,PET,"AV45 Co-registered, Averaged <- Adni AV45 4 X ...",Siemens/CTI,I391868,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,006_S_4153,MRI,AD,81.5,v21,9/16/2013,MT1; N3m <- MPRAGE,Philips Medical Systems,Processed,I391062,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3714,009_S_0751,ADNI,ADNI 2,M,57.5,CN,v31,9/17/2014,79.1,PET,"AV45 Co-registered, Averaged <- ADNIGO - AV45 ...",GE MEDICAL SYSTEMS,I445087,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,009_S_0751,MRI,CN,79.1,v31,9/04/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I451346,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3715,128_S_2045,ADNI,ADNI GO,M,80.3,EMCI,bl,10/28/2010,72.6,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I202039,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,128_S_2045,MRI,EMCI,72.5,scmri,8/26/2010,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I223513,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...

In [333]:
# add path to pet scans normalised to whole cerebellum, script cerebellum_normalisation. 
for i in range(0,np.shape(pet_mri_tab)[0]):
    name_pet = pet_mri_tab['Image.Data.ID'][i]+'_normalised.nii'
    filename = fnmatch.filter(os.listdir('/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25_10_23_registered_normalised_pet/'), name_pet)
    if len(filename)> 0:
        pet_mri_tab.loc[i,'PET_PATH_normalised'] = '/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25_10_23_registered_normalised_pet/' + filename[0]
    
    name_mri = pet_mri_tab['MRI_ID'][i]+'_registered.nii'
    filename = fnmatch.filter(os.listdir('/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25_10_23_registered_mri/'), name_mri)
    if len(filename)> 0:
        pet_mri_tab.loc[i,'MRI_PATH_registered'] = '/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25_10_23_registered_mri/' + filename[0]
     
    #print(i)

In [335]:
pet_mri_tab.shape

(4515, 27)

In [334]:
pet_mri_tab[pet_mri_tab['MRI_PATH_registered'].notna()]

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Study.Date,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_studydate,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH,MRI_PATH_registered
0,B59563700,A4,NaN,M,83.9,LEARN amyloidNE,SCV2,1/01/2016,84.4,PET,Florbetapir <- MNI_3DBRAIN_C),NaN,I1323673,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B59563700,MRI,LEARN amyloidNE,84.0,SCV4,1/01/2016,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1384728,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
1,023_S_4115,ADNI,ADNI 2,M,84.9,LMCI,v21,9/30/2013,69.7,PET,"AV45 Co-registered, Averaged <- PET Brain AV_4...",SIEMENS,I393755,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,023_S_4115,MRI,LMCI,69.7,v21,9/30/2013,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I398283,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3,032_S_4429,ADNI,ADNI 2,M,75.7,CN,v21,1/22/2014,79.2,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I413047,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,032_S_4429,MRI,CN,79.2,v21,1/21/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I416035,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4,B45524671,A4,NaN,M,71.4,amyloidE,SCV2,1/01/2016,82.5,PET,Florbetapir <- PET Scan,NaN,I1411194,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B45524671,MRI,amyloidE,82.6,SCV4,1/01/2016,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1364073,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
5,B14220479,A4,NaN,F,0.0,LEARN amyloidNE,SCV2,1/01/2016,71.8,PET,Florbetapir <- PET Scan,NaN,I1411241,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B14220479,MRI,LEARN amyloidNE,71.0,SCV4,1/01/2016,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1384417,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4508,067_S_0056,ADNI,ADNI 2,F,76.7,CN,v31,1/07/2015,78.9,PET,"AV45 Co-registered, Averaged <- AV45_Dyn_4x5mi...",SIEMENS,I468830,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,067_S_0056,MRI,CN,78.8,v31,12/15/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I468856,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4509,005_S_0553,ADNI,ADNI GO,M,65.3,CN,m48,12/15/2010,89.3,PET,"AV45 Co-registered, Averaged <- 20 min 3D AV45...",Siemens/CTI,I209032,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,005_S_0553,MRI,CN,89.2,m48,10/13/2010,MT1; GradWarp; N3m <- MP-RAGE REPEAT,GE MEDICAL SYSTEMS,Processed,I322397,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4510,006_S_4153,ADNI,ADNI 2,M,72.1,AD,v21,9/20/2013,81.5,PET,"AV45 Co-registered, Averaged <- Adni AV45 4 X ...",Siemens/CTI,I391868,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,006_S_4153,MRI,AD,81.5,v21,9/16/2013,MT1; N3m <- MPRAGE,Philips Medical Systems,Processed,I391062,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4512,009_S_0751,ADNI,ADNI 2,M,57.5,CN,v31,9/17/2014,79.1,PET,"AV45 Co-registered, Averaged <- ADNIGO - AV45 ...",GE MEDICAL SYSTEMS,I445087,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,009_S_0751,MRI,CN,79.1,v31,9/04/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I451346,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4514,128_S_2045,ADNI,ADNI GO,M,80.3,EMCI,bl,10/28/2010,72.6,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I202039,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,128_S_2045,MRI,EMCI,72.5,scmri,8/26/2010,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I223513,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...

In [117]:
pet_mri_tab = pet_mri_tab[pet_mri_tab['PET_PATH_normalised'].notna()]
pet_mri_tab.reset_index(drop=True, inplace = True)
pet_mri_tab = pet_mri_tab[pet_mri_tab['MRI_PATH_registered'].notna()]
pet_mri_tab.reset_index(drop=True, inplace = True)

In [118]:
#pet_mri_tab = pd.read_csv('pet_mri_pairs.csv')

In [119]:
pet_mri_tab.shape

(3451, 28)

In [360]:
pet_mri_tab['MRI_ID'].value_counts()

I494162     2
I498008     2
I1363560    1
I1364044    1
I1384602    1
           ..
I424734     1
I362972     1
I1384522    1
I1364673    1
I291002     1
Name: MRI_ID, Length: 3714, dtype: int64

In [361]:
pet_mri_tab

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Study.Date,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_studydate,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH
0,B59563700,A4,NaN,M,83.9,LEARN amyloidNE,SCV2,1/01/2016,84.4,PET,Florbetapir <- MNI_3DBRAIN_C),NaN,I1323673,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B59563700,MRI,LEARN amyloidNE,84.0,SCV4,1/01/2016,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1384728,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
1,023_S_4115,ADNI,ADNI 2,M,84.9,LMCI,v21,9/30/2013,69.7,PET,"AV45 Co-registered, Averaged <- PET Brain AV_4...",SIEMENS,I393755,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,023_S_4115,MRI,LMCI,69.7,v21,9/30/2013,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I398283,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
2,032_S_4429,ADNI,ADNI 2,M,75.7,CN,v21,1/22/2014,79.2,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I413047,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,032_S_4429,MRI,CN,79.2,v21,1/21/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I416035,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3,B45524671,A4,NaN,M,71.4,amyloidE,SCV2,1/01/2016,82.5,PET,Florbetapir <- PET Scan,NaN,I1411194,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B45524671,MRI,amyloidE,82.6,SCV4,1/01/2016,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1364073,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4,B14220479,A4,NaN,F,0.0,LEARN amyloidNE,SCV2,1/01/2016,71.8,PET,Florbetapir <- PET Scan,NaN,I1411241,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B14220479,MRI,LEARN amyloidNE,71.0,SCV4,1/01/2016,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1384417,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3711,067_S_0056,ADNI,ADNI 2,F,76.7,CN,v31,1/07/2015,78.9,PET,"AV45 Co-registered, Averaged <- AV45_Dyn_4x5mi...",SIEMENS,I468830,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,067_S_0056,MRI,CN,78.8,v31,12/15/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I468856,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3712,005_S_0553,ADNI,ADNI GO,M,65.3,CN,m48,12/15/2010,89.3,PET,"AV45 Co-registered, Averaged <- 20 min 3D AV45...",Siemens/CTI,I209032,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,005_S_0553,MRI,CN,89.2,m48,10/13/2010,MT1; GradWarp; N3m <- MP-RAGE REPEAT,GE MEDICAL SYSTEMS,Processed,I322397,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3713,006_S_4153,ADNI,ADNI 2,M,72.1,AD,v21,9/20/2013,81.5,PET,"AV45 Co-registered, Averaged <- Adni AV45 4 X ...",Siemens/CTI,I391868,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,006_S_4153,MRI,AD,81.5,v21,9/16/2013,MT1; N3m <- MPRAGE,Philips Medical Systems,Processed,I391062,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3714,009_S_0751,ADNI,ADNI 2,M,57.5,CN,v31,9/17/2014,79.1,PET,"AV45 Co-registered, Averaged <- ADNIGO - AV45 ...",GE MEDICAL SYSTEMS,I445087,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,009_S_0751,MRI,CN,79.1,v31,9/04/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I451346,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3715,128_S_2045,ADNI,ADNI GO,M,80.3,EMCI,bl,10/28/2010,72.6,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I202039,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,128_S_2045,MRI,EMCI,72.5,scmri,8/26/2010,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I223513,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...

In [300]:
meta4[meta4['Subject.ID']=='018_S_4597']

,Unnamed: 0,Unnamed: 0.1,Subject.ID,Project,Phase,Sex,Weight,Research.Group,Visit,Study.Date,Archive.Date,Age,Modality,Description,Type,Imaging.Protocol,Image.ID,VISCODE,Image.Data.ID,modality_subtype,PATH,year
27,30,44036,018_S_4597,ADNI,ADNI 2,F,55.5,EMCI,ADNI2 Year 1 Visit,3/11/2013,3/13/2013,69.5,MRI,MT1; N3m <- MPRAGE SENSE2,Processed,Philips Medical Systems,362978,v11,I362978,MPRAGE SENSE2,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2013
448,649,44035,018_S_4597,ADNI,ADNI 2,F,55.5,EMCI,ADNI2 Year 1 Visit,3/11/2013,3/11/2013,69.5,MRI,MPRAGE SENSE2,Original,Acquisition Plane=SAGITTAL;Slice Thickness=1.2...,362532,v11,I362532,MPRAGE SENSE2,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2013
2498,3612,44024,018_S_4597,ADNI,ADNI 2,F,56.7,EMCI,ADNI2 Month 3 MRI-New Pt,8/07/2012,8/07/2012,68.9,MRI,MPRAGE,Original,Acquisition Plane=SAGITTAL;Slice Thickness=1.2...,321921,v04,I321921,MPRAGE,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012
5666,8253,44010,018_S_4597,ADNI,ADNI 2,F,59.0,EMCI,ADNI2 Screening MRI-New Pt,3/14/2012,3/19/2012,68.5,MRI,MT1; N3m <- MPRAGE SENSE2,Processed,Philips Medical Systems,291022,v02,I291022,MPRAGE SENSE2,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012
8736,12727,44039,018_S_4597,ADNI,ADNI 2,F,55.5,EMCI,ADNI2 Year 1 Visit,3/11/2013,3/11/2013,69.5,MRI,MPRAGE,Original,Acquisition Plane=SAGITTAL;Slice Thickness=1.2...,362535,v11,I362535,MPRAGE,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2013
10815,15796,44008,018_S_4597,ADNI,ADNI 2,F,59.0,EMCI,ADNI2 Screening MRI-New Pt,3/14/2012,4/25/2012,68.5,MRI,MT1; N3m <- MPRAGE,Processed,Philips Medical Systems,300508,v02,I300508,MPRAGE,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012
12548,18386,44029,018_S_4597,ADNI,ADNI 2,F,56.7,EMCI,ADNI2 Month 3 MRI-New Pt,8/07/2012,8/07/2012,68.9,MRI,MPRAGE SENSE2,Original,Acquisition Plane=SAGITTAL;Slice Thickness=1.2...,321926,v04,I321926,MPRAGE SENSE2,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012
19825,29042,44014,018_S_4597,ADNI,ADNI 2,F,57.6,EMCI,ADNI2 Baseline-New Pt,6/05/2012,6/19/2012,68.8,PET,"AV45 Co-registered, Averaged <- 3D BRAIN AV-45...",Processed,GEMS,311324,v03,I311324,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012
26671,39086,44009,018_S_4597,ADNI,ADNI 2,F,59.0,EMCI,ADNI2 Screening MRI-New Pt,3/14/2012,3/14/2012,68.5,MRI,MPRAGE SENSE2,Original,Acquisition Plane=SAGITTAL;Slice Thickness=1.2...,290307,v02,I290307,MPRAGE SENSE2,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012
27444,40159,44052,018_S_4597,ADNI,ADNI 2,F,51.7,EMCI,ADNI2 Year 2 Visit,4/22/2014,4/25/2014,70.6,PET,"AV45 Co-registered, Averaged <- 3D BRAIN AV-45...",Processed,GEMS,421678,v21,I421678,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2014
27834,40729,44040,018_S_4597,ADNI,ADNI 2,F,55.5,EMCI,ADNI2 Year 1 Visit,3/11/2013,3/13/2013,69.5,MRI,MT1; N3m <- MPRAGE,Processed,Philips Medical Systems,362977,v11,I362977,MPRAGE,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2013
36579,53629,44030,018_S_4597,ADNI,ADNI 2,F,56.7,EMCI,ADNI2 Month 3 MRI-New Pt,8/07/2012,9/13/2012,68.9,MRI,MT1; N3m <- MPRAGE SENSE2,Processed,Philips Medical Systems,334102,v04,I334102,MPRAGE SENSE2,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012
39409,57859,44007,018_S_4597,ADNI,ADNI 2,F,59.0,EMCI,ADNI2 Screening MRI-New Pt,3/14/2012,3/14/2012,68.5,MRI,MPRAGE,Original,Acquisition Plane=SAGITTAL;Slice Thickness=1.2...,290304,v02,I290304,MPRAGE,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012
40708,59756,44025,018_S_4597,ADNI,ADNI 2,F,56.7,EMCI,ADNI2 Month 3 MRI-New Pt,8/07/2012,9/13/2012,68.9,MRI,MT1; N3m <- MPRAGE,Processed,Philips Medical Systems,334101,v04,I334101,MPRAGE,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2012

In [324]:
pet_mri_tab[pet_mri_tab['MRI_ID'] == 'I498008']

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Study.Date,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_studydate,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH
267,016_S_5031,ADNI,ADNI 2,F,66.7,EMCI,v21,5/14/2015,82.8,PET,"AV45 Co-registered, Averaged <- 016-S-5031 (AC...",SIEMENS,I500606,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,016_S_5031,MRI,EMCI,82.7,v21,5/04/2015,MT1; GradWarp; N3m <- Sag IR-SPGR,GE MEDICAL SYSTEMS,Processed,I498008,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
1728,016_S_5031,ADNI,ADNI 2,F,73.0,EMCI,v31,4/26/2016,83.7,PET,"AV45 Co-registered, Averaged <- 016-s-5031(AC)...",SIEMENS,I715555,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,016_S_5031,MRI,EMCI,82.7,v21,5/04/2015,MT1; GradWarp; N3m <- Sag IR-SPGR,GE MEDICAL SYSTEMS,Processed,I498008,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...

In [316]:
pet_mri_tab[pet_mri_tab['Subject.ID'] == '018_S_4597']

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Study.Date,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_studydate,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH
3265,018_S_4597,ADNI,ADNI 2,F,57.6,EMCI,v03,6/05/2012,68.8,PET,"AV45 Co-registered, Averaged <- 3D BRAIN AV-45...",GEMS,I311324,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,018_S_4597,MRI,EMCI,68.9,v04,8/07/2012,MT1; N3m <- MPRAGE SENSE2,Philips Medical Systems,Processed,I334102,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4571,018_S_4597,ADNI,ADNI 2,F,51.7,EMCI,v21,4/22/2014,70.6,PET,"AV45 Co-registered, Averaged <- 3D BRAIN AV-45...",GEMS,I421678,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,,,,NaN,,,,,,,

In [327]:
pet_mri_tab.VISCODE.value_counts()

SCV2    1661
v03      753
v21      503
bl       354
init     281
y2       244
v41      212
v11      156
v31      100
m48       82
v06       65
y4        44
m60       36
v51       18
m36        6
Name: VISCODE, dtype: int64

In [328]:
pet_mri_tab.MRI_VISCODE.value_counts()

SCV4    1661
v02      620
v21      493
init     275
y2       240
        ...
y1        11
v05        9
m36        6
m06        1
y3         1
Name: MRI_VISCODE, Length: 22, dtype: int64

In [329]:
pet_mri_tab[pet_mri_tab.VISCODE == pet_mri_tab.MRI_VISCODE]

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Study.Date,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_studydate,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH
1,023_S_4115,ADNI,ADNI 2,M,84.9,LMCI,v21,9/30/2013,69.7,PET,"AV45 Co-registered, Averaged <- PET Brain AV_4...",SIEMENS,I393755,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,023_S_4115,MRI,LMCI,69.7,v21,9/30/2013,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I398283,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
2,941_S_4036,ADNI,ADNI 3,M,88.0,EMCI,init,1/19/2018,80.7,PET,"AV45 Co-registered, Averaged <- ADNI3-BRAIN AV45",GE MEDICAL SYSTEMS,I966647,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,941_S_4036,MRI,EMCI,80.6,init,11/27/2017,Accelerated Sagittal MPRAGE,Acquisition Plane=SAGITTAL;Slice Thickness=1.2...,Original,I939342,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3,032_S_4429,ADNI,ADNI 2,M,75.7,CN,v21,1/22/2014,79.2,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I413047,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,032_S_4429,MRI,CN,79.2,v21,1/21/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I416035,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
6,153_S_4372,ADNI,ADNI 2,F,100.5,CN,v21,12/04/2013,72.2,PET,"AV45 Co-registered, Averaged <- PET Brain_Flor...",SIEMENS,I401653,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,153_S_4372,MRI,CN,72.2,v21,12/11/2013,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I416106,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
7,016_S_4902,ADNI,ADNI 2,F,68.0,LMCI,v31,12/29/2015,78.8,PET,"AV45 Co-registered, Averaged <- 016-S-4902(AC)...",SIEMENS,I600580,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,016_S_4902,MRI,LMCI,78.7,v31,12/18/2015,MT1; GradWarp; N3m <- Accelerated SAG IR-SPGR,GE MEDICAL SYSTEMS,Processed,I848420,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4508,067_S_0056,ADNI,ADNI 2,F,76.7,CN,v31,1/07/2015,78.9,PET,"AV45 Co-registered, Averaged <- AV45_Dyn_4x5mi...",SIEMENS,I468830,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,067_S_0056,MRI,CN,78.8,v31,12/15/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I468856,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4509,005_S_0553,ADNI,ADNI GO,M,65.3,CN,m48,12/15/2010,89.3,PET,"AV45 Co-registered, Averaged <- 20 min 3D AV45...",Siemens/CTI,I209032,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,005_S_0553,MRI,CN,89.2,m48,10/13/2010,MT1; GradWarp; N3m <- MP-RAGE REPEAT,GE MEDICAL SYSTEMS,Processed,I322397,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4510,006_S_4153,ADNI,ADNI 2,M,72.1,AD,v21,9/20/2013,81.5,PET,"AV45 Co-registered, Averaged <- Adni AV45 4 X ...",Siemens/CTI,I391868,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,006_S_4153,MRI,AD,81.5,v21,9/16/2013,MT1; N3m <- MPRAGE,Philips Medical Systems,Processed,I391062,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4511,941_S_4036,ADNI,ADNI 3,M,88.0,EMCI,y2,3/06/2020,82.9,PET,"AV45 Co-registered, Averaged <- ADNI3-BRAIN AV45",GE MEDICAL SYSTEMS,I1302729,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,941_S_4036,MRI,EMCI,82.8,y2,2/26/2020,Accelerated Sagittal MPRAGE,Acquisition Plane=SAGITTAL;Slice Thickness=1.0...,Original,I1296964,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4512,009_S_0751,ADNI,ADNI 2,M,57.5,CN,v31,9/17/2014,79.1,PET,"AV45 Co-registered, Averaged <- ADNIGO - AV45 ...",GE MEDICAL SYSTEMS,I445087,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,009_S_0751,MRI,CN,79.1,v31,9/04/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I451346,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...

In [52]:
# remove scans with bad registration
meta_qc = pd.read_csv('/csc/epitkane/home/atagmazi/ADDL_pipeline/scripts/registration/metafile_ADDLpipeline_abeta_mri_27_05_2025_afterQC.csv',header=[0], index_col=[0])
pet_mri_tab = pet_mri_tab[pet_mri_tab['Image.Data.ID'].isin(meta_qc['Image.Data.ID'])].copy()
pet_mri_tab.reset_index(drop=True, inplace = True)

In [53]:
pet_mri_tab

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Study.Date,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_studydate,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH
0,B59563700,A4,NaN,M,83.9,LEARN amyloidNE,SCV2,1/01/2016,84.4,PET,Florbetapir <- MNI_3DBRAIN_C),NaN,I1323673,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B59563700,MRI,LEARN amyloidNE,84.0,SCV4,1/01/2016,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1384728,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
1,023_S_4115,ADNI,ADNI 2,M,84.9,LMCI,v21,9/30/2013,69.7,PET,"AV45 Co-registered, Averaged <- PET Brain AV_4...",SIEMENS,I393755,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,023_S_4115,MRI,LMCI,69.7,v21,9/30/2013,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I398283,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
2,032_S_4429,ADNI,ADNI 2,M,75.7,CN,v21,1/22/2014,79.2,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I413047,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,032_S_4429,MRI,CN,79.2,v21,1/21/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I416035,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3,B45524671,A4,NaN,M,71.4,amyloidE,SCV2,1/01/2016,82.5,PET,Florbetapir <- PET Scan,NaN,I1411194,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B45524671,MRI,amyloidE,82.6,SCV4,1/01/2016,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1364073,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
4,B14220479,A4,NaN,F,0.0,LEARN amyloidNE,SCV2,1/01/2016,71.8,PET,Florbetapir <- PET Scan,NaN,I1411241,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B14220479,MRI,LEARN amyloidNE,71.0,SCV4,1/01/2016,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1384417,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3421,067_S_0056,ADNI,ADNI 2,F,76.7,CN,v31,1/07/2015,78.9,PET,"AV45 Co-registered, Averaged <- AV45_Dyn_4x5mi...",SIEMENS,I468830,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,067_S_0056,MRI,CN,78.8,v31,12/15/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I468856,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3422,005_S_0553,ADNI,ADNI GO,M,65.3,CN,m48,12/15/2010,89.3,PET,"AV45 Co-registered, Averaged <- 20 min 3D AV45...",Siemens/CTI,I209032,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,005_S_0553,MRI,CN,89.2,m48,10/13/2010,MT1; GradWarp; N3m <- MP-RAGE REPEAT,GE MEDICAL SYSTEMS,Processed,I322397,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3423,006_S_4153,ADNI,ADNI 2,M,72.1,AD,v21,9/20/2013,81.5,PET,"AV45 Co-registered, Averaged <- Adni AV45 4 X ...",Siemens/CTI,I391868,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,006_S_4153,MRI,AD,81.5,v21,9/16/2013,MT1; N3m <- MPRAGE,Philips Medical Systems,Processed,I391062,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3424,009_S_0751,ADNI,ADNI 2,M,57.5,CN,v31,9/17/2014,79.1,PET,"AV45 Co-registered, Averaged <- ADNIGO - AV45 ...",GE MEDICAL SYSTEMS,I445087,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,009_S_0751,MRI,CN,79.1,v31,9/04/2014,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I451346,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3425,128_S_2045,ADNI,ADNI GO,M,80.3,EMCI,bl,10/28/2010,72.6,PET,"AV45 Co-registered, Averaged <- ADNI Brain PET...",Siemens ECAT,I202039,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,128_S_2045,MRI,EMCI,72.5,scmri,8/26/2010,MT1; GradWarp; N3m <- MPRAGE,SIEMENS,Processed,I223513,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...

In [ ]:
#split data on train and test subsets
train_size = 0.8
train_end = int(len(pet_mri_tab)*train_size)
t = int(0.8*train_end) #!!
v = int(0.2*train_end) 
#DATADIR = r"/csc/epitkane/data/ADNI/AD_DL_03_11_2021/"
print(f'train set size = {t}')

In [ ]:
'''pet_mri_tab['pet_min'] = 0
pet_mri_tab['pet_max'] = 0
pet_mri_tab['pet_95q'] = 0
pet_mri_tab['pet_99q'] = 0

pet_mri_tab['mri_min'] = 0
pet_mri_tab['mri_max'] = 0
pet_mri_tab['mri_95q'] = 0
pet_mri_tab['mri_99q'] = 0


i_invalid = []
pet_all_values = []
mri_all_values = []
for i in range(pet_mri_tab.shape[0]):
    img_pet = nib.load(pet_mri_tab['PET_PATH_normalised'][i])
        
    img_mri = nib.load(pet_mri_tab['MRI_PATH_registered'][i])
    
    image_pet = np.asarray(img_pet.get_fdata())
    image_mri = np.asarray(img_mri.get_fdata())
    
    if np.isnan(image_pet).any() or np.isnan(image_mri).any():
        print(f"Skipping index {i}: NaNs detected in PET or MRI scan.")
        i_invalid.append(i)
    elif np.max(image_pet) <= 0 or np.max(image_mri) <= 0:  # Changed from == 0 to <= 0
        print(f"Skipping index {i}: Empty or non-positive PET or MRI scan.")
        i_invalid.append(i)
    else:
        pet_mri_tab.loc[i,'pet_min'] = np.min(image_pet)
        pet_mri_tab.loc[i,'pet_max'] = np.max(image_pet)
        pet_mri_tab.loc[i,'pet_99q'] = np.percentile(image_pet, 99)
        pet_mri_tab.loc[i,'pet_999q'] = np.percentile(image_pet, 99.9)
        
        # Store min & max values (ensures outliers are captured)
        #pet_all_values.append(image_pet.min())
        while i<=t:
            pet_all_values.append(image_pet.max())
        # Sample a subset of pixels (reduces memory usage)
            pet_all_values.extend(np.random.choice(image_pet.flatten(), size=min(10000, image_pet.size), replace=False))
        #pet_all_values.extend(image_pet[image_pet > 0].flatten())


        
        pet_mri_tab.loc[i,'mri_min'] = np.min(image_mri)
        pet_mri_tab.loc[i,'mri_max'] = np.max(image_mri)
        pet_mri_tab.loc[i,'mri_99q'] = np.percentile(image_mri, 99)
        pet_mri_tab.loc[i,'mri_999q'] = np.percentile(image_mri, 99.9)
        # Store min & max values (ensures outliers are captured)
        #mri_all_values.append(image_mri.min())
        while i <=t:
            mri_all_values.append(image_mri.max())
        # Sample a subset of pixels (reduces memory usage)
            mri_all_values.extend(np.random.choice(image_mri.flatten(), size=min(10000, image_mri.size), replace=False))
        #mri_all_values.extend(image_mri[image_mri > 0].flatten())

        
    print(i)
    
print(i_invalid)    
pet_minimum = np.min(pet_mri_tab['pet_min'])
pet_maximum = np.max(pet_mri_tab['pet_max'])
mri_minimum = np.min(pet_mri_tab['mri_min'])
mri_maximum = np.max(pet_mri_tab['mri_max'])
print(f'MinMax computation is done! PET minimum is {pet_minimum}, PET maximum is {pet_maximum}. MRI minimum is {mri_minimum}, MRI maximum is {mri_maximum}')
'''

/tmp/ipykernel_43436/1921735778.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.908689022064209' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pet_mri_tab.loc[i,'pet_max'] = np.max(image_pet)
/tmp/ipykernel_43436/1921735778.py:28: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.7029719293117513' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pet_mri_tab.loc[i,'pet_95q'] = np.percentile(image_pet, 95)
/tmp/ipykernel_43436/1921735778.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.2386636161804194' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pet_mri_tab.loc[i,'pet_99q'] = np.percentile(image_pet, 99)
/tmp/ipykernel_43436/1921735778.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1022.2391357421875' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pet_mri_tab.loc[i,'mri_max'] = np.max(image_mri)
/tmp/ipykernel_43436/1921735778.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '362.2067810058593' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pet_mri_tab.loc[i,'mri_95q'] = np.percentile(image_mri, 95)
/tmp/ipykernel_43436/1921735778.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '582.3908209228513' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pet_mri_tab.loc[i,'mri_99q'] = np.percentile(image_mri, 99)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52

/tmp/ipykernel_43436/1921735778.py:31: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.8371753692626953' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pet_mri_tab.loc[i,'mri_min'] = np.min(image_mri)

53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190
3191
3192
3193
3194
3195
3196
3197
3198
3199
3200
3201
3202
3203
3204
3205
3206
3207
3208
3209
3210
3211
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3225
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3250
3251
3252
3253
3254
3255
3256
3257
3258
3259
3260
3261
3262
3263
3264
3265
3266
3267
3268
3269
3270
3271
3272
3273
3274
3275
3276
3277
3278
3279
3280
3281
3282
3283
3284
3285
3286
3287
3288
3289
3290
3291
3292
3293
3294
3295
3296
3297
3298
3299
3300
3301
3302
3303
3304
3305
3306
3307
3308
3309
3310
3311
3312
3313
3314
3315
3316
3317
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392
3393
3394
3395
3396
3397
3398
3399
3400
3401
3402
3403
3404
3405
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
3437
3438
3439
3440
3441
3442
3443
3444
3445
3446
3447
3448
3449
3450
3451
3452
3453
3454
3455
3456
3457
3458
3459
3460
3461
3462
3463
3464
3465
3466
3467
3468
3469
3470
3471
3472
3473
3474
3475
3476
3477
3478
3479
3480
3481
3482
MinMax computation is done! PET minimum is 0.0, PET maximum is 1270.4830322265625. MRI minimum is -3.1125051118005393e+38, MRI maximum is 3.2012842609971632e+38

In [ ]:

logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger(__name__)
def process_row(i, pet_path, mri_path):
    result = {
        'i': i,
        'pet_min': 0,
        'pet_max': 0,
        'pet_90q': 0,
        'pet_95q': 0,
        'pet_99q': 0,
        'pet_999q': 0,
        'mri_min': 0,
        'mri_max': 0,
        'mri_90q': 0,
        'mri_95q': 0,
        'mri_99q': 0,
        'mri_999q': 0,
        'pet_values': [],
        'mri_values': [],
        'invalid': False
    }
    logger.info(f"Processing index {i}")  # Log each index being processed

    try:
        image_pet = np.asarray(nib.load(pet_path).get_fdata())
        image_mri = np.asarray(nib.load(mri_path).get_fdata())
        
        if np.isnan(image_pet).any() or np.isnan(image_mri).any():
            result['invalid'] = True
            return result
        elif np.max(image_pet) <= 0 or np.max(image_mri) <= 0:
            result['invalid'] = True
            return result
        
        result['pet_min'] = np.min(image_pet)
        result['pet_max'] = np.max(image_pet)
        result['pet_90q'] = np.percentile(image_pet, 90)
        result['pet_95q'] = np.percentile(image_pet, 95)
        result['pet_99q'] = np.percentile(image_pet, 99)
        result['pet_999q'] = np.percentile(image_pet, 99.9)
        if i <= t:
            result['pet_values'] = np.random.choice(image_pet.flatten(), size=min(10000, image_pet.size), replace=False)
        
        result['mri_min'] = np.min(image_mri)
        result['mri_max'] = np.max(image_mri)
        result['mri_90q'] = np.percentile(image_mri, 90)
        result['mri_95q'] = np.percentile(image_mri, 95)
        result['mri_99q'] = np.percentile(image_mri, 99)
        result['mri_999q'] = np.percentile(image_mri, 99.9)
        if i <= t:
            result['mri_values'] = np.random.choice(image_mri.flatten(), size=min(10000, image_mri.size), replace=False)
        
    except Exception as e:
        print(f"Error processing index {i}: {e}")
        result['invalid'] = True
    
    return result

# Number of workers to run in parallel (adjust based on your CPU)
n_jobs = 8

results = Parallel(n_jobs=n_jobs)(
    delayed(process_row)(i, pet_mri_tab['PET_PATH_normalised'][i], pet_mri_tab['MRI_PATH_registered'][i])
    for i in range(pet_mri_tab.shape[0])
)

# Rebuild dataframe from results
for res in results:
    i = res['i']
    if not res['invalid']:
        pet_mri_tab.loc[i, 'pet_min'] = res['pet_min']
        pet_mri_tab.loc[i, 'pet_max'] = res['pet_max']
        pet_mri_tab.loc[i, 'pet_90q'] = res['pet_90q']
        pet_mri_tab.loc[i, 'pet_95q'] = res['pet_95q']
        pet_mri_tab.loc[i, 'pet_99q'] = res['pet_99q']
        pet_mri_tab.loc[i, 'pet_999q'] = res['pet_999q']
        
        pet_mri_tab.loc[i, 'mri_min'] = res['mri_min']
        pet_mri_tab.loc[i, 'mri_max'] = res['mri_max']
        pet_mri_tab.loc[i, 'mri_90q'] = res['mri_90q']
        pet_mri_tab.loc[i, 'mri_95q'] = res['mri_95q']
        pet_mri_tab.loc[i, 'mri_99q'] = res['mri_99q']
        pet_mri_tab.loc[i, 'mri_999q'] = res['mri_999q']
        
pet_all_values = np.concatenate([r['pet_values'] for r in results if not r['invalid']])
mri_all_values = np.concatenate([r['mri_values'] for r in results if not r['invalid']])
i_invalid = [r['i'] for r in results if r['invalid']]

# Final min/max stats
print(f"Invalid indexes: {i_invalid}")
print(f"PET min: {pet_mri_tab['pet_min'].min()}, max: {pet_mri_tab['pet_max'].max()}")
print(f"MRI min: {pet_mri_tab['mri_min'].min()}, max: {pet_mri_tab['mri_max'].max()}")

In [1]:
# Drop invalid rows
pet_mri_tab.drop(index=i_invalid, inplace=True)
pet_mri_tab.reset_index(drop=True, inplace=True)

print(f"Remaining valid rows: {pet_mri_tab.shape[0]}")

NameError: name 'pet_mri_tab' is not defined

In [ ]:
pet_all_values = np.array(pet_all_values)
mri_all_values = np.array(mri_all_values)

p_quant90 = np.quantile(pet_all_values, 0.90)
m_quant90 = np.quantile(mri_all_values, 0.90)

p_quant95 = np.quantile(pet_all_values, 0.95)
m_quant95 = np.quantile(mri_all_values, 0.95)


p_quant99 = np.quantile(pet_all_values, 0.99)
m_quant99 = np.quantile(mri_all_values, 0.99)

p_quant999 = np.quantile(pet_all_values, 0.999)
m_quant999 = np.quantile(mri_all_values, 0.999)

p_mean = np.mean(pet_all_values)
m_mean = np.mean(mri_all_values)

p_std = np.std(pet_all_values)
m_std = np.std(mri_all_values)

p_median = np.median(pet_all_values)
m_median = np.median(mri_all_values)

p_iqr = iqr(pet_all_values, rng=(25, 75))
m_iqr = iqr(mri_all_values, rng=(25, 75))

p_after_clip = np.clip(pet_all_values, 0, p_quant999, out=None)
m_after_clip = np.clip(mri_all_values, 0, m_quant999, out=None)
p_mean_clip = np.mean(p_after_clip)
m_mean_clip = np.mean(m_after_clip)
p_std_clip = np.std(p_after_clip)
m_std_clip = np.std(m_after_clip)
p_min_clip = np.min(p_after_clip)
m_min_clip = np.min(m_after_clip)
p_max_clip = np.max(p_after_clip)
m_max_clip = np.max(m_after_clip)


np.savez("stats_train.npz",
         p_quant90=p_quant90,
         m_quant90=m_quant90,
         p_quant95=p_quant95,
         m_quant95=m_quant95,
         p_quant99=p_quant99, 
         m_quant99=m_quant99,
         p_quant999=p_quant999, 
         m_quant999=m_quant999,
         p_mean=p_mean, 
         m_mean=m_mean, 
         p_std=p_std, 
         m_std=m_std,
         p_median=p_median, 
         m_median=m_median, 
         p_iqr=p_iqr, 
         m_iqr=m_iqr,
         p_mean_clip=p_mean_clip, 
         m_mean_clip=m_mean_clip,
         p_std_clip=p_std_clip, 
         m_std_clip=m_std_clip,
         p_mim_clip=p_min_clip, 
         m_min_clip=m_min_clip,
         p_max_clip=p_max_clip, 
         m_max_clip=m_max_clip
        )

In [ ]:
plt.figure(figsize=(10, 5))

# PET Histogram
plt.subplot(2, 2, 1)
plt.hist(pet_all_values, bins=500, color='blue', alpha=0.7, edgecolor='black')
plt.xlabel("Pixel Value")
plt.ylabel("Frequency")
plt.title("PET Image Histogram")

# MRI Histogram
plt.subplot(2, 2, 2)
plt.hist(mri_all_values, bins=500, color='red', alpha=0.7, edgecolor='black')
plt.xlabel("Pixel Value")
plt.ylabel("Frequency")
plt.title("MRI Image Histogram")


plt.subplot(2, 2, 3)
plt.hist(np.log1p(pet_all_values), bins=500, color='blue', alpha=0.7, edgecolor='black')  # Log scale on Y-axis
plt.xlabel("Log Pixel Value")
plt.ylabel("Frequency")
plt.title("PET Image Histogram")



plt.subplot(2, 2, 4)
plt.hist(np.log1p(mri_all_values), bins=500, color='red', alpha=0.7, edgecolor='black')
plt.xlabel("Log Pixel Value")
plt.ylabel("Frequency")
plt.title("MRI Image Histogram")


# Save and show the plot
plt.tight_layout()
plt.savefig("pixels_value_histograms.png")  # Save the figure
plt.show()  # Display the plot

In [ ]:
plt.figure(figsize=(10, 5))

# PET Histogram
plt.subplot(2, 2, 1)
plt.hist(p_after_clip, bins=500, color='blue', alpha=0.7, edgecolor='black')
plt.xlabel("Pixel Value")
plt.ylabel("Frequency")
plt.title("PET Image Histogram")

# MRI Histogram
plt.subplot(2, 2, 2)
plt.hist(m_after_clip, bins=500, color='red', alpha=0.7, edgecolor='black')
plt.xlabel("Pixel Value")
plt.ylabel("Frequency")
plt.title("MRI Image Histogram")


plt.subplot(2, 2, 3)
plt.hist(np.log1p(p_after_clip), bins=500, color='blue', alpha=0.7, edgecolor='black')  # Log scale on Y-axis
plt.xlabel("Log Pixel Value")
plt.ylabel("Frequency")
plt.title("PET Image Histogram")



plt.subplot(2, 2, 4)
plt.hist(np.log1p(m_after_clip), bins=500, color='red', alpha=0.7, edgecolor='black')
plt.xlabel("Log Pixel Value")
plt.ylabel("Frequency")
plt.title("MRI Image Histogram")


# Save and show the plot
plt.tight_layout()
plt.savefig("pixels_value_histograms_clip999.png")  # Save the figure
plt.show()  # Display the plot

In [22]:
i_invalid #pet_mri_tab.drop(index = i_invalid)

[]

In [41]:
#pet_mri_tab = pet_mri_tab[pet_mri_tab.mri_min >= 0]
pet_mri_tab.reset_index(drop=True, inplace = True)

In [42]:
pet_minimum = np.min(pet_mri_tab['pet_min'])
pet_maximum = np.max(pet_mri_tab['pet_max'])
mri_minimum = np.min(pet_mri_tab['mri_min'])
mri_maximum = np.max(pet_mri_tab['mri_max'])
print(f'MinMax computation is done! PET minimum is {pet_minimum}, PET maximum is {pet_maximum}. MRI minimum is {mri_minimum}, MRI maximum is {mri_maximum}')

MinMax computation is done! PET minimum is 0.0, PET maximum is 1270.4830322265625. MRI minimum is 0.0, MRI maximum is 26299.69921875

In [32]:
pet_mri_tab.to_csv('pet_mri_pairs.csv')

In [44]:
pet_mri_tab.shape

(3471, 30)

In [45]:
suc

4983

In [46]:
er

3232

In [47]:
pet_meta[pet_meta['Subject.ID'] == 'B10256269']

,Unnamed: 0,Subject.ID,Project,Phase,Sex,Weight,Research.Group,Visit,Study.Date,Archive.Date,Age,Modality,Description,Type,Imaging.Protocol,Image.ID,VISCODE,Image.Data.ID,modality_subtype,PATH,year
3742,217585,B10256269,A4,NaN,F,60.3,LEARN amyloidNE,SCV2,1/01/2016,7/20/2020,65.8,PET,Florbetapir <- LZAZ- (AC),Processed,NaN,1321180,SCV2,I1321180,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,2016

In [48]:
pet_mri_tab[pet_mri_tab['Subject.ID'] == 'B10256269']

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH,MRI_PATH_registered,PET_PATH_normalised,pet_min,pet_max,mri_min,mri_max
1990,B10256269,A4,NaN,F,60.3,LEARN amyloidNE,SCV2,65.8,PET,Florbetapir <- LZAZ- (AC),NaN,I1321180,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B10256269,MRI,LEARN amyloidNE,66.0,SCV4,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1384839,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,0.0,2.555523,0.206524,471.969879

In [49]:
pet_mri_tab.Phase.value_counts()

ADNI 2     1749
ADNI GO     210
ADNI 1       24
Name: Phase, dtype: int64

In [50]:
pet_mri_tab.Project.value_counts()

ADNI    1983
A4      1488
Name: Project, dtype: int64

In [22]:
pet_mri_tab[pet_mri_tab.Phase == 'ADNI 1'].MRI_Type.value_counts()

Processed    132
Name: MRI_Type, dtype: int64

In [23]:
pet_mri_tab[pet_mri_tab.Phase == 'ADNI 2'].MRI_Type.value_counts()

Processed    1840
Name: MRI_Type, dtype: int64

In [24]:
pet_mri_tab[pet_mri_tab.Phase == 'ADNI GO'].MRI_Type.value_counts()

Processed    251
Name: MRI_Type, dtype: int64

In [25]:
pet_mri_tab[pet_mri_tab.Phase == 'ADNI 3'].MRI_Type.value_counts()

Original    971
Name: MRI_Type, dtype: int64

In [26]:
pet_mri_tab[pet_mri_tab.Project == 'A4'].MRI_Type.value_counts()

Processed    1788
Name: MRI_Type, dtype: int64

In [165]:
pet_mri_tab.MRI_Modality.value_counts()

MRI    4982
Name: MRI_Modality, dtype: int64

In [ ]:
pet_mri_tab[pet_mri_tab.Phase == 'ADNI 1'][pet_mri_tab.MRI_Type == 'Processed']

In [31]:
pet_mri_tab[pet_mri_tab.Phase == 'ADNI 3'][pet_mri_tab.MRI_Type == 'Processed']

/csc/epitkane/home/atagmazi/.conda/envs/atagmazi_gpu8/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [Subject.ID, Project, Phase, Sex, Weight, Research.Group, VISCODE, Age, Modality, Description, Imaging.Protocol, Image.Data.ID, modality_subtype, PATH, MRI_subID, MRI_Modality, MRI_Research.Group, MRI_Age, MRI_VISCODE, MRI_Description, MRI_Imaging.protocol, MRI_Type, MRI_ID, MRI_PATH]
Index: []

In [32]:
pet_mri_tab[pet_mri_tab['Research.Group'] == 'amyloidE']

,Subject.ID,Project,Phase,Sex,Weight,Research.Group,VISCODE,Age,Modality,Description,Imaging.Protocol,Image.Data.ID,modality_subtype,PATH,MRI_subID,MRI_Modality,MRI_Research.Group,MRI_Age,MRI_VISCODE,MRI_Description,MRI_Imaging.protocol,MRI_Type,MRI_ID,MRI_PATH
3731,B10081264,A4,NaN,F,72.6,amyloidE,SCV2,67.9,PET,Florbetapir <- PET Scan,NaN,I1410362,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B10081264,MRI,amyloidE,67.9,SCV4,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1364445,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3733,B10102783,A4,NaN,F,0.0,amyloidE,SCV2,72.6,PET,Florbetapir <- PET Scan,NaN,I1410368,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B10102783,MRI,amyloidE,72.7,SCV4,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1363140,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3735,B10108368,A4,NaN,F,69.0,amyloidE,SCV2,66.8,PET,Florbetapir <- PET Scan,NaN,I1410363,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B10108368,MRI,amyloidE,66.9,SCV4,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1364240,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3736,B10117310,A4,NaN,M,112.1,amyloidE,SCV2,69.4,PET,Florbetapir <- FRAME 1,NaN,I1324825,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B10117310,MRI,amyloidE,69.5,SCV4,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1363742,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
3748,B10350512,A4,NaN,M,0.0,amyloidE,SCV2,70.9,PET,Florbetapir <- PET Scan,NaN,I1410364,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B10350512,MRI,amyloidE,71.1,SCV4,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1364363,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8196,B99696480,A4,NaN,F,95.3,amyloidE,SCV2,74.6,PET,Florbetapir <- LZAZ-34 (AC),NaN,I1324700,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B99696480,MRI,amyloidE,74.6,SCV4,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1364178,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
8199,B99711873,A4,NaN,M,62.1,amyloidE,SCV2,73.4,PET,Florbetapir <- PET Scan,NaN,I1410706,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B99711873,MRI,amyloidE,73.5,SCV4,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1363372,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
8208,B99860801,A4,NaN,M,53.8,amyloidE,SCV2,71.7,PET,"Florbetapir <- [AC],,,2,,,",NaN,I1324682,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B99860801,MRI,amyloidE,71.8,SCV4,T1; DeFaced <- Accelerated Sag IR-FSPGR,NaN,Processed,I1363279,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
8209,B99870985,A4,NaN,M,0.0,amyloidE,SCV2,71.4,PET,Florbetapir <- PET Scan,NaN,I1411052,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B99870985,MRI,amyloidE,71.4,SCV4,T1; DeFaced <- Sagittal 3D Accelerated MPRAGE,NaN,Processed,I1362921,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...
8212,B99957366,A4,NaN,M,82.0,amyloidE,SCV2,83.2,PET,Florbetapir <- PET Scan,NaN,I1410790,AV45,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...,B99957366,MRI,amyloidE,83.3,SCV4,T1; GradWarp; DeFaced <- Sagittal 3D Accelerat...,NaN,Processed,I1362922,/csc/epitkane/data/ADNI_A4/ADNI_16_04_22_A4_25...

In [33]:
pet_mri_tab[pet_mri_tab.Project == 'ADNI'].MRI_Description.value_counts()

Accelerated Sagittal MPRAGE             662
MT1; GradWarp; N3m <- MPRAGE            444
MT1; GradWarp; N3m <- MPRAGE GRAPPA2    400
MT1; N3m <- MPRAGE                      202
MT1; N3m <- MPRAGE SENSE2               180
                                       ...
MT1; N3m <- MPRAGE REPEAT ASO             1
MT1; N3m <- ADNI SH    MPRAGE ASOX2       1
MPR; ; N3 <- ADNI SH    MPRAGE ASO        1
MT1; GradWarp; N3m <- MP-RAGE repeat      1
3D MPRAGE                                 1
Name: MRI_Description, Length: 84, dtype: int64

In [34]:
import seaborn as sns
import matplotlib.pyplot as plt

In [35]:
pet_mri_tab['Research.Group'].value_counts().values

array([1247, 1150,  722,  541,  487,  364,  251,  220])

In [36]:
pet_mri_tab['Research.Group'].value_counts()

amyloidE           1247
CN                 1150
EMCI                722
LEARN amyloidNE     541
MCI                 487
LMCI                364
AD                  251
SMC                 220
Name: Research.Group, dtype: int64

In [ ]:
plt.figure(figsize=(15,6))

ax = sns.violinplot(x="Research.Group", y="Age", data=pet_mri_tab)

# Calculate number of obs per group & median to position labels
medians = pet_mri_tab.groupby(['Research.Group'])['Age'].max().values
nobs = pet_mri_tab['Research.Group'].value_counts(sort=False).values
nobs = [str(x) for x in nobs.tolist()]
nobs = ["n: " + i for i in nobs]
 
# Add text to the figure
pos = range(len(nobs))
for tick, label in zip(pos, ax.get_xticklabels()):
   ax.text(pos[tick], medians[tick] + 0.03, nobs[tick],
            horizontalalignment='left',
            size=13,
            color='blue',
            weight='semibold')
#plt.show()
plt.savefig('samples_dist.png')

In [ ]:
pd.set_option('display.max_rows', None)
pet_mri_tab[pet_mri_tab.Project == 'A4'].Age.value_counts()

In [ ]:
pet_mri_tab[pet_mri_tab.Age == 0.0]

In [ ]:
pet_mri_tab.Age